#!/bin/bash

ds=$(pwd -P | sed -e s@.\*/store/user/`whoami`@@ | sed -e "s@/\(.*\)/\(.*\)/\(.*\)@/\1/`whoami`-\2-\3/USER@")
echo $ds
echo make sure the DS is right, hit enter to proceed
read
dass ana03 file $ds > das
cat das | cut -d / -f 8 | sort > das_bn
ls --color=no -1 *root | sort > all
diff das_bn all | grep \> | sed -e 's/> //' > tomv
wc -l tomv das_bn all
echo ok? enter to proceed
read
mkdir no
mv `cat tomv` no/
