#!/usr/bin/env python

import os
from sys import argv
from JMTucker.Tools.CRAB3ToolsBase import crab_dirs_from_argv
from JMTucker.Tools import colors

dirs = crab_dirs_from_argv()

def simple_cmd(cmd_fmt):
    for d in dirs:
        cmd = cmd_fmt % d
        verbose = True
        if verbose:
            print colors.bold(cmd)
        code = os.system(cmd)
        if verbose:
            color = colors.boldred if code != 0 else colors.green
            print color('exit code: %s' % code)
            print

if 'st' in argv or 'stat' in argv:
    simple_cmd('crab status -d %s')
elif 'kl' in argv or 'kill' in argv:
    simple_cmd('crab kill -d %s')
elif 'out' in argv:
    simple_cmd('crab out -d %s --xrootd')
elif 'get' in argv:
    simple_cmd('crab out -d %s')
elif 'res' in argv:
    simple_cmd('crab resubmit -d %s')
elif 'rep' in argv:
    simple_cmd('crab report -d %s')
elif 'hl' in argv:
    os.system('mkdir haddlogs ; mv -i *.haddlog haddlogs/')
else:
    raise ValueError("didn't understand command, argv was %r", argv)
