#!/usr/bin/env python

import os, sys, re
from JMTucker.Tools.CRABTools import *

print 'warning: this only works for remoteGlidein jobs'

gets = {}
scps = {}

psx = crab_popen('ps xww').split('\n')

for line in psx:
    ls = line.split()
    if ' python ' in line and not ' sh ' in line and ' -get' in line:
        i = ls.index('-c') + 1
        dir = ls[i]
        jobs = crab_jobs_from_list(ls[i+1:])
        assert not gets.has_key(dir)
        gets[dir] = jobs

r = re.compile(r'_(\d+).(tgz|xml)')
for line in psx:
    ls = line.split()
    if 'gsiscp' in line and not 'sh -c' in line:
        mo = r.search(line)
        if mo is not None:
            dir = os.path.normpath(ls[-1].replace('/res', ''))
            num = int(mo.group(1))
            assert not scps.has_key(dir)
            scps[dir] = num

for scp_dir in sorted(scps.keys()):
    for get_dir, jobs in gets.iteritems():
        if scp_dir.endswith(get_dir):
            print get_dir, jobs.index(scps[scp_dir])+1, '/', len(jobs)

