#!/usr/bin/env python

import os, sys, random
from JMTucker.Tools.CRABTools import decrabify_list

temp_fn = 'ff.tmp'

total_njobs = 0

curr_status = None
curr_lines = []
curr_nbatch = 0
curr_njobs = 0

for line in open('screen-exchange'):
    line = line.strip()
    if not line:
        continue

    if line.startswith('Retrieved'):
        if curr_status is not None:
            total_njobs += curr_njobs
            print '\ndone with status %s with %i batches and %i jobs' % (curr_status, curr_nbatch, curr_njobs)
            if not raw_input('run crjobprobs?').strip():
                open(temp_fn, 'wt').write('\n'.join(curr_lines))
                os.system('crjobprobs < %s' % temp_fn)

        curr_status = line
        curr_lines = []
        curr_nbatch = 0
        curr_njobs = 0
    else:
        curr_lines.append(line)
        batch, jobs = line.split()
        jobs = decrabify_list(jobs)

        if curr_nbatch == 0:
            job = random.choice(jobs)
            print '\n' + curr_status, line, '->', job
            if not raw_input('run crlog?').strip():
                os.system('crlog %s %s' % (batch, job))

        curr_nbatch += 1
        curr_njobs += len(jobs)

print 'total jobs', total_njobs

os.remove(temp_fn)
