#!/usr/bin/env python

import os, sys
from JMTucker.Tools.CRABTools import *

if '-all' in sys.argv:
    working_dir = crab_working_dirs()
    sys.argv.remove('-all')
else:
    working_dir = last_crab_working_dir()
jobs = 'all'

if len(sys.argv) > 2:
    working_dir, jobs = sys.argv[1:3]
elif len(sys.argv) > 1:
    arg = sys.argv[1]
    if os.path.isdir(arg):
        working_dir = arg
    else:
        jobs = arg

if working_dir is None:
    raise ValueError('need to specify working_dir')

if type(working_dir) != type([]):
    working_dir = [working_dir]

for d in working_dir:
    os.system('crab -c %s -getoutput %s' % (d, jobs))
