#!/usr/bin/env python

import os
import glob
import sys
import JMTucker.Tools.argparse as argparse
from JMTucker.Tools.CRAB3ToolsSh import is_crab_working_dir, crab_hadd

parser = argparse.ArgumentParser(description = 'crhadd: hadd the files from a crab directory',
                                 usage = '%(prog)s [options] crab_dirs')

parser.add_argument('positional', nargs='*', help='The crab directories.')

parser.add_argument('--chunk-size', default=900, type=int,
                    help='The maximum number files hadded at once.')

options = parser.parse_args()

if len(options.positional) == 0:
    print 'Required positional args missing: at least one crab directory\n'
    parser.print_help()
    sys.exit(1)

########################################################################

crab_dirs = options.positional

ok = False

for x in crab_dirs:
    if is_crab_working_dir(x):
        ok = True
        crab_hadd(x, chunk_size=options.chunk_size)
    elif os.path.isdir(x):
        # if we have a dir of crab dirs, crab_hadd all the directories in it.
        sub_dirs = [d for d in glob.glob(os.path.join(x, '*')) if is_crab_working_dir(d)]
        for y in sub_dirs:
            ok = True
            crab_hadd(y, new_dir=x, chunk_size=options.chunk_size)

if not ok:
    raise ValueError('no crab dirs found in argv')
