#!/usr/bin/env python

from JMTucker.Tools.general import reverse_readline
from JMTucker.Tools.CRABTools import *

try:
    d = crab_dir_from_argv()
except CrabError:
    sys.stderr.write('Usage: crlaststatus <crab directory> [list of jobs]\n    Only one crab directory is allowed at a time.\n')
    sys.exit(1)

jobs = ['%i ' % j for j in crab_jobs_from_argv()]
if jobs:
    print 'filtering for %i jobs' % len(jobs)

log_fn = os.path.join(d, 'log/crab.log')

lines = []
found = False

for i, line in enumerate(reverse_readline(log_fn)):
    lines.append(line)
    if '-status' in line:
        found = True
        break

if not found:
    raise ValueError('never found "-status" in %s' % log_fn)

lines.reverse()

for line in lines:
    if jobs and not any(line.startswith(j) for j in jobs):
        continue
    print line
