#!/usr/bin/env python

import sys
from JMTucker.Tools.CRABTools import CrabError, crab_dir_from_argv, crab_jobs_from_argv

try:
    d = crab_dir_from_argv()
except CrabError:
    sys.stderr.write('Usage: crlogs <crab directory> <list of jobs>\n    Only one crab directory is allowed at a time.\n')
    sys.exit(1)

for job in crab_jobs_from_argv():
    print '%s/res/CMSSW_%i.stdout' % (d, job),
