#!/usr/bin/env python

import sys
from JMTucker.Tools.CRABTools import CrabError, crab_dirs_from_argv, crab_jobs_from_argv

dirs = crab_dirs_from_argv()
jobs = crab_jobs_from_argv()

if len(dirs) == 0 or (len(jobs) > 1 and len(jobs)):
    sys.stderr.write('Usage: crlogs <crab directories> [list of jobs]\n    If list of jobs provided, only one crab directory allowed.\n')
    sys.exit(1)

if len(dirs) > 1:
    for d in dirs:
        print '%s/log/crab.log' % d,
else:
    for job in jobs:
        print '%s/res/CMSSW_%i.stdout' % (d, job),
