#!/usr/bin/env python

import os, sys
from JMTucker.Tools.CRABTools import crab_dirs_from_argv

for d in crab_dirs_from_argv():
    # JMTBAD Make this check that all R_0 jobs were published...
    cmd = 'crab -c %s -publish' % d
    print cmd
    os.system(cmd)
