#!/usr/bin/env python

import os, sys
from JMTucker.Tools.CRABTools import *

cmds = '''
touch crtidied
tar czf share_condor_temp.tgz share/.condor_temp
rm -r share/.condor_temp
tar czf stdouterrxmlwatch.tgz res/*.stdout res/*.stderr res/*.xml res/Watchdog_* res/no_inp*
rm res/*.stdout res/*.stderr res/*.xml res/Watchdog_*
rm -r res/no_inp*
rm -r res/Submission_*
rm -r res/crabcheckoutputat*
rm -r res/crrejobat*
gzip log/crab.log
'''.split('\n')

wd = os.getcwd()

for d in crab_dirs_from_argv():
    print d
    os.chdir(d)
    for cmd in cmds:
        print_run_cmd(cmd)
    print
    os.chdir(wd)
