#!/usr/bin/env python

import sys, os
argv = sys.argv[1:]
interactive = ''
if '-i' in argv:
    interactive = '-i'
    argv.remove('-i')
cmd = 'python %s $CMSSW_BASE/src/DVCode/Tools/python/CRAB3Tools.py ' % interactive + ' '.join(argv)
print cmd
os.system(cmd)
