#!/usr/bin/env python

import os, sys
from pprint import pprint
from DVCode.Tools.general import bool_from_argv
from DVCode.Tools.CondorTools import cs_dirs_from_argv

stdout = bool_from_argv('stdout')
edit = bool_from_argv('edit')
if stdout and edit:
    raise ValueError('cannot edit when dumping to stdout')

wds = cs_dirs_from_argv()
if not wds:
    print 'No condor dirs in argv\n'
    sys.exit(1)

for wd in wds:
    orig_fn = os.path.join(wd, 'cs_filelist.py')
    new_fn  = os.path.join(wd, 'cs_filelist2.py')

    execfile(orig_fn)

    if stdout:
        f = sys.stdout
    else:
        f = open(new_fn, 'wt')

    f.write('_l = ')
    pprint(_l, f)
    f.write('\ndef get(i): return _l[i]\n')

    if not stdout:
        f.close()

    if edit:
        os.system('emacs -nw %s %s' % (orig_fn, new_fn))
        if os.system('diff %s %s' % (orig_fn, new_fn)) != 0:
            raw_input('hit enter to replace, ^C to cancel ')
            bak_fn = os.path.join(wd, 'cs_filelist.py.bak')
            while os.path.isfile(bak_fn):
                bak_fn += '.bak'
            os.rename(orig_fn, bak_fn)
            os.rename(new_fn, orig_fn)
