#!/usr/bin/env python

import sys
from DVCode.Tools.CondorTools import *

prio = sys.argv[1]
if not (prio.startswith('+') or prio.startswith('-')):
    sys.exit('usage: cs_prio prio wd1 [wd2 ...]\n  prio is either +n or -n')

for wd in cs_dirs_from_argv():
    if not cs_done(wd):
        cs_prio(wd, prio)
