#!/usr/bin/env python

import os, sys
from glob import glob
from JMTucker.Tools.general import bool_from_argv
from JMTucker.Tools.CondorTools import cs_dirs_from_argv
from JMTucker.Tools import colors

if len(sys.argv) < 2:
    print 'usage: cs_tidy wd [wd2 ...]'
    sys.exit(1)

rm_root_files = bool_from_argv('rm_root_files')

cmds = [x.strip() for x in '''
touch cs_tidied
touch cs_tidied_started
tar --remove-files -czf stdouterrlogxmlpublish.tgz stdout.* stderr.* log.* fjr*xml PUBLISH
touch cs_tidied_finished
'''.split('\n') if x.strip()]

if rm_root_files:
    cmds.append('rm -r *.root')

prev_wd = os.getcwd()

for wd in cs_dirs_from_argv():
    print colors.bold(wd)
    if os.path.isfile(os.path.join(wd, 'cs_tidied')):
        if not os.path.isfile(os.path.join(wd, 'cs_tidied_finished')):
            print colors.red('cs_tidied but no _finished?')
        else:
            print 'already cs_tidied, skipping'
            continue
    os.chdir(wd)
    for cmd in cmds:
        #print cmd
        if cmd.startswith('tar') and glob('publish*txt'):
            cmd.replace('PUBLISH', 'publish*txt')
        os.system(cmd)
    print
    os.chdir(prev_wd)
