#!/usr/bin/env python

import sys
from DVCode.Tools.general import typed_from_argv
from DVCode.Tools.DBS import das_query

instance = typed_from_argv(int)
if instance is None:
    instance = 'global'

dq = das_query(instance)

def form_query(cmd, query_fmt, nargs):
    query = None
    try:
        i = sys.argv.index(cmd)
    except ValueError:
        i = -1
    ok = i >= 0 and i + nargs < len(sys.argv)
    if ok:
        query = query_fmt % tuple(sys.argv[i+1:i+1+nargs])
    return query

def intable(x):
    try:
        int(float(x))
        return True
    except ValueError:
        return False

query_infos = [
    (('ds', 'dataset dataset=%s', 1), lambda s: s),
    (('file', 'file dataset=%s', 1), lambda s: s.endswith('.root')),
    (('run', 'run dataset=%s', 1), lambda s: intable(s)),
    (('lumi', 'lumi dataset=%s', 1), lambda s: intable(s)),
    (('nevents', 'dataset dataset=%s | grep dataset.nevents', 1), lambda s: intable(s)),
    (('site', 'site dataset=%s', 1), lambda s: s),
    (('parent', 'parent dataset=%s', 1), lambda s: s),
    ]

found = False

for query_info, line_filter in query_infos:
    query = form_query(*query_info)
    if query is not None:
        print '\n'.join(dq(query, line_filter))
        found = True
        break

if not found:
    raise ValueError('did not understand command')

'''
    if 'size' in sys.argv:
        sys.argv.remove('size')
        c = 'find sum(file.size) where dataset=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'file' in sys.argv:
        sys.argv.remove('file')
        c = 'find file where dataset=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'filenev' in sys.argv:
        sys.argv.remove('filenev')
        c = 'find file,file.numevents where dataset=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'filenevsz' in sys.argv:
        sys.argv.remove('filenevsz')
        c = 'find file,file.numevents,file.size where dataset=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'site' in sys.argv:
        sys.argv.remove('site')
        c = 'find site where dataset=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'nevents' in sys.argv:
        sys.argv.remove('nevents')
        c = 'find sum(file.numevents) where dataset=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'nevent' in sys.argv:
        sys.argv.remove('nevent')
        c = 'find file.numevents where file=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'ds' in sys.argv:
        sys.argv.remove('ds')
        c = 'find dataset where dataset like "*%s*"' % sys.argv[1]
        cmd = cmd % c
    elif 'dss' in sys.argv:
        sys.argv.remove('dss')
        c = 'find dataset where dataset like "%s"' % sys.argv[1]
        cmd = cmd % c
    elif 'dsfile' in sys.argv:
        sys.argv.remove('dsfile')
        c = 'find dataset where file="%s"' % sys.argv[1]
        cmd = cmd % c
    elif 'dsrun' in sys.argv:
        sys.argv.remove('dsrun')
        c = 'find dataset where run=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'filerun' in sys.argv:
        sys.argv.remove('filerun')
        c = 'find file where dataset="%s" and run=%s' % (sys.argv[1], sys.argv[2])
        cmd = cmd % c
    elif 'filerunls' in sys.argv:
        sys.argv.remove('filerunls')
        c = 'find file where dataset="%s" and run=%s and lumi=%s' % (sys.argv[1], sys.argv[2], sys.argv[3])
        cmd = cmd % c
    elif 'fileparent' in sys.argv:
        sys.argv.remove('fileparent')
        c = 'find file.parent where file="%s"' % sys.argv[1]
        cmd = cmd % c
    elif 'runrange' in sys.argv:
        sys.argv.remove('runrange')
        c = 'find min(run),max(run) where dataset=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'rel' in sys.argv:
        sys.argv.remove('rel')
        c = 'find release where dataset=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'run' in sys.argv:
        sys.argv.remove('run')
        c = 'find run where dataset=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'runfile' in sys.argv:
        sys.argv.remove('runfile')
        c = 'find run where file=%s' % sys.argv[1]
        cmd = cmd % c
    elif 'pick' in sys.argv:
        n = sys.argv.index('pick')
        r,l = sys.argv[n+1:n+3]
        r,l = int(r), int(l)
        del sys.argv[n:n+3]
        c = 'find file where dataset=%s and run=%i and lumi=%i' % (sys.argv[1], r, l)
        cmd = cmd % c
'''
