#!/usr/bin/env python

import sys
from itertools import combinations
from FWCore.PythonUtilities.LumiList import LumiList
from JMTucker.Tools import colors

ret = 0

fns = sys.argv[1:]
for fna,fnb in combinations(fns, 2):
    lla = LumiList(fna)
    llb = LumiList(fnb)
    x = lla & llb
    if x.compactList:
        ret += 1
        print colors.bold('problem #%i:' % ret)
        print fna
        print fnb
        print x
        print

sys.exit(ret)
