#!/usr/bin/env python

import os
import glob
import sys
import JMTucker.Tools.argparse as argparse
from JMTucker.Tools.CRAB3ToolsSh import is_crab_working_dir, crab_hadd_args, crab_hadd_files, crab_hadd
from JMTucker.Tools.CondorTools import is_cs_dir, cs_hadd_args, cs_hadd_files, cs_hadd
from JMTucker.Tools.general import touch
from JMTucker.Tools.hadd import HaddlogParser
from JMTucker.Tools import eos, colors

parser = argparse.ArgumentParser(description = 'mhadd: hadd the files from condor/crab directories',
                                 usage = '%(prog)s [options] condor_or_crab_dirs')

parser.add_argument('positional', nargs='*', help='The condor/crab directories.')

parser.add_argument('--chunk-size', default=900, type=int,
                    help='The maximum number files hadded at once.')
parser.add_argument('--pattern',
                    help='Glob-style pattern to filter the files, useful if there are multiple files output per job.')
parser.add_argument('--no-lpc-shortcut', action='store_false', dest='lpc_shortcut', default=True,
                    help='(Only for crab dirs) Most of the time files went to FNAL LPC EOS, this is used to bypass talking to the crab server--turn off if needed.')
parser.add_argument('--ignore-done', action='store_true', default=False,
                    help='Ignore the done marker files and try to hadd whatever specified.')
parser.add_argument('--only-notdones', action='store_true', default=False,
                    help='Only do not-dones (implies --overwrite and --ignore-done).')
parser.add_argument('-f', '--overwrite', action='store_true', default=False,
                    help='If the output file exists, overwrite it (really, delete it before hadd ever sees it).')
parser.add_argument('-o', '--output-dir',
                    help='Path for the output files. (Can be an xrootd url, e.g. root://cmseos.fnal.gov//store/user/tucker/outputdir.) If doing dirs of dirs, directories are created under the output dir corresponding to the basenames of the toplevel dirs. If the toplevel dirs are not unique, you will have a bad time.')

options = parser.parse_args()

if len(options.positional) == 0:
    print 'Required positional args missing: at least one crab directory\n'
    parser.print_help()
    sys.exit(1)

if options.only_notdones:
    options.ignore_done = True
    options.overwrite = True

########################################################################

wds = options.positional
found_one = False

def hadd_(is_crab, *args, **kwargs):
    global found_one
    found_one = True

    done = True
    working_dir = args[0]
    if not os.path.isfile(os.path.join(working_dir, 'mmon_done')):
        if options.ignore_done:
            done = False
        else:
            print colors.yellow('skipping %s since it is not marked done (--ignore-done to skip this check)' % working_dir)
            return

    kwargs['chunk_size'] = options.chunk_size
    kwargs['pattern'] = options.pattern

    if is_crab:
        kwargs['lpc_shortcut'] = options.lpc_shortcut
        hadd_args, hadd_files, hadd = crab_hadd_args, crab_hadd_files, crab_hadd
    else:
        hadd_args, hadd_files, hadd = cs_hadd_args, cs_hadd_files, cs_hadd

    new_dir = kwargs.get('new_dir', None)
    if options.output_dir:
        if new_dir:
            base_new_dir = os.path.basename(new_dir)
            new_dir = os.path.join(options.output_dir, base_new_dir)
        else:
            new_dir = options.output_dir
    kwargs['new_dir'] = new_dir

    working_dir, new_name, new_dir = hadd_args(working_dir, kwargs.get('new_name', None), new_dir)

    if new_dir and '/store/' in new_dir:
        exists, mkdir, rm = eos.exists, eos.mkdir, eos.rm
    else:
        exists, mkdir, rm = os.path.exists, os.mkdir, os.remove

    if new_dir and not exists(new_dir):
        mkdir(new_dir)

    notdone_fn = new_name + '.notdone'
    if options.only_notdones and not os.path.isfile(notdone_fn):
        print colors.yellow('ignoring %s' % new_name)
        return

    if not done:
        touch(notdone_fn)

    if exists(new_name):
        if options.overwrite:
            print colors.yellow('overwriting existing file %s' % new_name)
            rm(new_name)
        else:
            log_fn = new_name + '.haddlog'
            njobs = hadd_files(working_dir, **kwargs)[0]
            if not os.path.isfile(log_fn):
                log_njobs = 1 # assume 1 file copied
            else:
                p = HaddlogParser(new_name + '.haddlog')
                log_njobs = p.num_sources
            if log_njobs != njobs:
                print colors.red('skipping existing file %s (for which num sources %i != njobs %i)' % (new_name, log_njobs, njobs))
            else:
                print colors.yellow('skipping existing file %s (which looks complete by njobs and haddlog)' % new_name)
            return

    hadd(*args, **kwargs)


for x in wds:
    is_crab = is_crab_working_dir(x)
    if is_crab or is_cs_dir(x):
        hadd_(is_crab, x)
    elif os.path.isdir(x):
        # if we have a dir of condor/crab dirs, cs/crab_hadd all the directories in it.
        for d in glob.glob(os.path.join(x, '*')):
            is_crab = is_crab_working_dir(d)
            if is_crab or is_cs_dir(d):
                hadd_(is_crab, d, new_dir=x)

if not found_one:
    raise ValueError('no condor/crab dirs found in argv')
