#!/usr/bin/env python

import os
from pprint import pprint
from JMTucker.Tools.CondorTools import cs_dirs_from_argv
from JMTucker.Tools.CRAB3Tools import crab_dirs_from_argv, crab_status
from JMTucker.Tools.general import to_pickle

cr_dirs = crab_dirs_from_argv()
cs_dirs = cs_dirs_from_argv()
wds = cr_dirs + cs_dirs

if not wds:
    sys.exit('usage: mjson condor_or_crab_dirs')

obj = {}

for wd in wds:
    awd = os.path.abspath(wd)
    if wd in cr_dirs:
        obj[awd] = (1, crab_status(wd, long=True)[1]['jobs'])
    else:
        raise ValueError('condor not implemented yet')
        obj[awd] = (0, None)

to_pickle(obj, 'mjson.gzpickle')
