#!/usr/bin/env python

# for x in $(find $crd -type d -name crab\* -o -name condor\* ) ; do if [[ ! -f $x/mtidied ]]; then echo $x; fi; done

import os, sys
from glob import glob
from DVCode.Tools.general import bool_from_argv, touch
from DVCode.Tools.CondorTools import cs_dirs_from_argv
from DVCode.Tools.CRAB3ToolsBase import crab_dirs_from_argv
from DVCode.Tools import colors

if len(sys.argv) < 2:
    print 'usage: mtidy wd [wd2 ...]'
    sys.exit(1)

rm_root_files = bool_from_argv('rm_root_files') or bool_from_argv('rm')
cr_cmds = ['gzip crab.log mmon_last', 'tar --remove-files -czf inputs.tgz inputs/']
cs_cmds = ['tar --remove-files -czf mtidied.tgz stdout.* stderr.* log.* EXTRA']
if rm_root_files:
    cs_cmds.append('rm -r *.root')

cr_dirs = crab_dirs_from_argv()
if cr_dirs and rm_root_files:
    print colors.yellow('rm_root_files does nothing for crab dirs')

prev_wd = os.getcwd()
    
for wd in cr_dirs + cs_dirs_from_argv():
    is_cr = wd in cr_dirs

    print colors.bold(wd)
    if os.path.isfile(os.path.join(wd, 'mtidied')):
        if not os.path.isfile(os.path.join(wd, 'mtidied_finished')):
            print colors.red('mtidied but no _finished?')
        else:
            print 'already mtidied, skipping'
            continue

    os.chdir(wd)
    touch('mtidied')
    touch('mtidied_started')
    for cmd in (cr_cmds if is_cr else cs_cmds):
        #print cmd
        if not is_cr and cmd.endswith('EXTRA'):
            extra = ' '.join([x for x in 'fjr*xml', 'publish*txt', 'resub*', 'mmon_last' if glob(x)])
            cmd = cmd.replace('EXTRA', extra)
        os.system(cmd)
    touch('mtidied_finished')
    os.chdir(prev_wd)
