#!/usr/bin/env python

import sys
from FWCore.PythonUtilities.LumiList import LumiList
from JMTucker.Tools.ROOTTools import *

tree_path = sys.argv[1]
fns = sys.argv[2:]

rl = set()
for fn in fns:
    f = ROOT.TFile.Open(fn)
    rl.update(detree(f.Get(tree_path), 'run:lumi'))

ll = LumiList(lumis=list(rl))
print ll
