#!/bin/bash

if [[ -n $NUM_SCRAM_JOBS ]]; then
    export NUM_SCRAM_JOBS=4
fi

if [[ ! -d $1 ]]; then
    echo first argument must be a path
    exit 1
fi

path=$1
shift

if [[ $1 == "touch" ]]; then
    shift
    for x in $(find $path -name BuildFile.xml); do
        echo touch $x
        touch $x
    done
fi

pushd $path
cmd="scramv1 b -j $NUM_SCRAM_JOBS $@"
echo $cmd
eval $cmd
ECODE=$?
popd
exit $ECODE
