import os, sys, base64, re, cPickle as pickle
from collections import defaultdict
from gzip import GzipFile
from itertools import product
from pprint import pprint
from modify import set_mfv_neutralino, set_gluino_ddbar

# !!! DO NOT CHANGE ANYTHING THAT CHANGES WHICH JOB IS WHICH SAMPLE ONCE BATCHES ARE RUN WITH THAT SCANPACK !!!
# unless you delete all the output from that scanpack.
# Make a new subclass and go from there. E.g. scanpackbase100epj exists to just change events_per_job going forward.
# Adding helper functions or anything that has no side effects to scanpackbase is fine.

# conventions:
# kind are one of the set_* functions from modify
# tau are float, in mm like pythia and modify
# mass are int, GeV

class scanpackbase(object):
    jobs_per_batch = 5000
    events_per_job = 200

    def __init__(self):
        self.name = self.__class__.__name__
        self.build_samples()
        self.njobs = 0
        self.job2isample = []
        for isample, (kind,tau,mass) in enumerate(self.samples):
            eps, epj = self.events_per_sample(kind,tau,mass), self.events_per_job
            assert eps >= epj and eps % epj == 0
            njobs = eps / epj

            self.njobs += njobs
            self.job2isample += [isample]*njobs
        assert self.njobs > 0

        self.jobs_in_last_batch = self.njobs % self.jobs_per_batch
        if self.jobs_in_last_batch == 0:
            self.jobs_in_last_batch = self.jobs_per_batch

        int_ceil = lambda x,y: (x+y-1)/y
        self.nbatches = int_ceil(self.njobs, self.jobs_per_batch)
        self.ibatch = 0

    def build_samples(self):
        if hasattr(self, 'samples_string'):
            details = pickle.loads(base64.b64decode(self.samples_string))
            details = sorted(details.items())
            self.samples = []
            self.__eps = {}
            for (kind_name, tau, mass), events in details:
                d = eval(kind_name), tau, mass
                self.samples.append(d)
                self.__eps[d] = events
        else:
            self.samples = list(product(self.kinds, self.taus, self.masses))

    def events_per_sample(self, kind, tau, mass):
        assert hasattr(self, 'samples_string')
        return self.__eps[(kind,tau,mass)]

    def sample(self, batch, job):
        assert 0 <= batch < self.nbatches
        assert 0 <= job < self.jobs_per_batch
        if batch == self.nbatches - 1:
            assert job < self.jobs_in_last_batch
        return self.samples[self.job2isample[batch * self.jobs_per_batch + job]]

    def sample_name(self, kind, tau, mass):
        '''Samples-style naming'''
        kind = kind.__name__
        if kind == 'set_mfv_neutralino':
            kind = 'mfv_neu'
        elif kind == 'set_gluino_ddbar':
            kind = 'mfv_ddbar'
        else:
            raise ValueError('dunno %s' % kind)
        tau = int(tau*1000)
        return '%s_tau%05ium_M%04i' % (kind, tau, mass)

    def sample_details(self, name):
        '''inverse of sample_name'''
        kind, tau, mass = name.rsplit('_',2)
        if kind == 'mfv_neu':
            kind = set_mfv_neutralino
        elif kind == 'mfv_ddbar':
            kind = set_gluino_ddbar
        else:
            raise NameError('dunno %s' % kind)
        assert tau.startswith('tau') and tau.endswith('um')
        tau = int(tau[3:].replace('um','')) / 1000.
        assert mass.startswith('M')
        mass = int(mass[1:])
        return kind, tau, mass

    def isample(self, kind, tau, mass):
        target = kind, tau, mass
        for i,x in enumerate(self.samples):
            if x == target:
                return i

    def __iter__(self):
        for self.ibatch in xrange(self.nbatches):
            yield self

    @property
    def nevents(self):
        if self.ibatch < self.nbatches - 1:
            njobs = self.jobs_per_batch
        else:
            njobs = self.jobs_in_last_batch
        return self.events_per_job * njobs

    @property
    def batch_name(self):
        return '%s_%s' % (self.name, self.ibatch)

class scanpacktest(scanpackbase):
    kinds = [set_mfv_neutralino, set_gluino_ddbar]
    taus = [tau/1000. for tau in [100,10000]]
    masses = [400, 800]

    jobs_per_batch = 50
    events_per_job = 10
    def events_per_sample(self, kind, tau, mass):
        return 100

class scanpacktest2(scanpackbase):
    kinds = [set_mfv_neutralino, set_gluino_ddbar]
    taus = [tau/1000. for tau in [300,10000]]
    masses = [600, 800]

    jobs_per_batch = 39
    def events_per_sample(self, kind, tau, mass):
        return 1000

class scanpack1(scanpackbase):
    kinds = [set_mfv_neutralino, set_gluino_ddbar]
    taus = [tau/1000. for tau in range(100, 1000, 300) + range(1000, 40000, 3000) + range(40000, 1000001, 160000)]
    masses = range(300, 600, 100) + range(600, 3001, 200)

    def events_per_sample(self, kind, tau, mass):
        return 10000

class scanpackbase100epj(scanpackbase):
    events_per_job = 100

class scanpack1_100epj(scanpack1, scanpackbase100epj): # lol
    pass

class scanpack1p5(scanpackbase100epj):
    # missing stats from scanpack1 run--don't need to run this for scanpack1_hip, there jobs almost fully completed
    samples_string = 'gAJ9cQEoVRJzZXRfbWZ2X25ldXRyYWxpbm9xAkdAOQAAAAAAAE0oCodNKApoAkdAMwAAAAAAAE3wCodN8ApVEHNldF9nbHVpbm9fZGRiYXJxA0dAaQAAAAAAAE0sAYdLyGgCR0AcAAAAAAAATfAKh004GGgDRz/mZmZmZmZmTdAHh0vIaAJHQEKAAAAAAABN0AeHTbAEaANHQDMAAAAAAABNmAiHTVgCaAJHP9mZmZmZmZpN8AqHTQgHaAJHQCoAAAAAAABNKAqHTZgIaANHQGkAAAAAAABNWAKHTZABaAJHQEQAAAAAAABN8AqHTbAEaANHQIBAAAAAAABNQAaHTUgNaAJHQBAAAAAAAABN6AOHTVgCaANHQHaAAAAAAABNKAqHTTARaANHQDYAAAAAAABNuAuHTegDaAJHQIVAAAAAAABNKAqHTbAEaAJHQDAAAAAAAABNKAqHTegDaAJHQHaAAAAAAABNmAiHTSADaANHP/AAAAAAAABNeAWHS8hoA0dARAAAAAAAAE0sAYdNIANoA0dAMAAAAAAAAE0IB4dLyGgCRz/mZmZmZmZmTdAHh03oA2gDRz/ZmZmZmZmaTSgKh03IGWgDRz/ZmZmZmZmaTVgCh00wEWgDRz+5mZmZmZmaTdAHh02IE2gDR0BEAAAAAAAATdAHh03wCmgCR0BEAAAAAAAATegDh00gA2gCR0AQAAAAAAAATQgHh03wCmgCR0A/AAAAAAAATUAGh0vIaANHQBwAAAAAAABNIAOHS8hoAkdAMwAAAAAAAE14BYdNWAJoA0dARAAAAAAAAE2QAYdLyGgDRz/wAAAAAAAATdAHh02QAWgCR0AzAAAAAAAATUAGh03oA2gDRz/ZmZmZmZmaTbAEh03gFWgDR0BpAAAAAAAATdAHh00IB2gCR0CAQAAAAAAATbAEh00IB2gCR0BpAAAAAAAATSgKh014BWgDRz/ZmZmZmZmaTfAKh00AGWgCR0CPQAAAAAAATfAKh01oEGgCR0AzAAAAAAAATbgLh00oCmgDR0AqAAAAAAAATXgFh01YAmgCR0AcAAAAAAAATUAGh01IDWgCR0A/AAAAAAAATfAKh014BWgCR0AcAAAAAAAATbgLh034EWgDR0AkAAAAAAAATSgKh0vIaANHQDYAAAAAAABNsASHS8hoAkdAMAAAAAAAAE3oA4dNkAFoA0dAPwAAAAAAAE0oCodNWAJoAkc/8AAAAAAAAE3QB4dNQAZoAkdARAAAAAAAAE1ABodNkAFoA0dAdoAAAAAAAE0sAYdLyGgCR0BBAAAAAAAATQgHh00gA2gCR0AwAAAAAAAATbAEh03oA2gDR0CFQAAAAAAATXgFh01gCWgCR0CPQAAAAAAATbAEh00IB2gDR0AcAAAAAAAATSgKh03oA2gCR0CPQAAAAAAATWAJh03YDmgDR0CFQAAAAAAATSADh00oCmgDR0AQAAAAAAAATegDh01YAmgDRz+5mZmZmZmaTQgHh034EWgDR0A/AAAAAAAATZgIh01YAmgCR0A8AAAAAAAATUAGh01YAmgDR0CFQAAAAAAATVgCh01ABmgCRz/wAAAAAAAATWAJh014BWgDRz/ZmZmZmZmaTZgIh03AEmgCR0BBAAAAAAAATXgFh0vIaANHQEEAAAAAAABNuAuHTaAPaAJHQD8AAAAAAABNuAuHTXgFaANHQDkAAAAAAABNYAmHS8hoAkdAhUAAAAAAAE0sAYdNIANoAkdAMAAAAAAAAE3wCodNCAdoAkdAPAAAAAAAAE3oA4dN0AdoA0dAMAAAAAAAAE3QB4dLyGgCR0AQAAAAAAAATWAJh00oCmgDR0B2gAAAAAAATZABh02QAWgCRz/mZmZmZmZmTbgLh03QB2gCR0BBAAAAAAAATegDh02QAWgDRz/ZmZmZmZmaTSwBh024C2gDR0BEAAAAAAAATQgHh00IB2gDR0A2AAAAAAAATUAGh02QAWgDR0A8AAAAAAAATZgIh0vIaAJHQGkAAAAAAABN0AeHTZABaAJHQDYAAAAAAABNuAuHTZgIaANHP9mZmZmZmZpNYAmHTVgbaAJHQIBAAAAAAABNmAiHTZgIaAJHQCQAAAAAAABNuAuHTegDaANHP9mZmZmZmZpN9AGHTYAMaAJHQDYAAAAAAABNCAeHTbAEaAJHQBwAAAAAAABNeAWHTYAMaAJHQDMAAAAAAABNCAeHTbAEaANHQIBAAAAAAABNuAuHTRAOaANHQHaAAAAAAABNQAaHTSgKaAJHQHaAAAAAAABNLAGHS8hoAkdAj0AAAAAAAE1ABodN0AdoAkc/uZmZmZmZmk3QB4dN6ANoAkdAOQAAAAAAAE3QB4dN0AdoA0dAJAAAAAAAAE2YCIdNsARoAkdANgAAAAAAAE14BYdLyGgDR0AqAAAAAAAATWAJh014BWgCR0AqAAAAAAAATdAHh02QAWgCR0AcAAAAAAAATQgHh02gD2gCRz+5mZmZmZmaTbgLh02wBGgCR0A8AAAAAAAATbAEh024C2gDR0B2gAAAAAAATegDh02wBGgDRz+5mZmZmZmaTZABh02QAWgCR0BCgAAAAAAATSgKh01YAmgDR0CFQAAAAAAATdAHh01oEGgCR0CFQAAAAAAATegDh02wBGgDR0A8AAAAAAAATUAGh0vIaAJHQI9AAAAAAABN9AGHTSADaANHQGkAAAAAAABNuAuHTUgNaAJHP7mZmZmZmZpNKAqHTSADaAJHQEEAAAAAAABNuAuHTXgFaANHP7mZmZmZmZpNuAuHTTgYaANHQCQAAAAAAABNQAaHTZABaAJHQEEAAAAAAABNQAaHS8hoAkdAaQAAAAAAAE0gA4dLyGgDR0CFQAAAAAAATbAEh01oEGgCR0A5AAAAAAAATVgCh0vIaAJHQDYAAAAAAABN8AqHTSgKaAJHQDwAAAAAAABN8AqHTSADaAJHQIBAAAAAAABNQAaHTXgFaANHQEKAAAAAAABN8AqHTRAOaAJHQDYAAAAAAABNQAaHTZABaANHQEEAAAAAAABNYAmHTdAHaANHQGkAAAAAAABNeAWHTVgCaAJHQDkAAAAAAABNeAWHTbAEaAJHQIpAAAAAAABN8AqHTUgNaAJHQIBAAAAAAABNeAWHTbAEaANHQHaAAAAAAABNCAeHTdgOaAJHQDAAAAAAAABNuAuHTbgLaANHQBAAAAAAAABNQAaHS8hoA0dAKgAAAAAAAE24C4dNuAtoAkdAgEAAAAAAAE3wCodN0AdoA0c/uZmZmZmZmk30AYdNCAdoAkdAEAAAAAAAAE24C4dNwBJoA0dAEAAAAAAAAE3wCodN6ANoA0dAKgAAAAAAAE1ABodNkAFoAkdANgAAAAAAAE2wBIdNWAJoAkc/5mZmZmZmZk1gCYdN0AdoA0dAQQAAAAAAAE2YCIdNuAtoA0dAEAAAAAAAAE1gCYdN6ANoAkdAPAAAAAAAAE14BYdNsARoAkc/5mZmZmZmZk3wCodN0AdoAkc/2ZmZmZmZmk1gCYdNkAFoA0dAgEAAAAAAAE14BYdNYAloAkdAikAAAAAAAE2wBIdNQAZoA0dARAAAAAAAAE1ABodNuAtoAkdAikAAAAAAAE0gA4dNIANoAkc/8AAAAAAAAE0IB4dNeAVoA0dAJAAAAAAAAE24C4dNIANoA0dARAAAAAAAAE14BYdN6ANoA0dAPwAAAAAAAE1ABodNkAFoAkdARAAAAAAAAE0oCodN6ANoAkc/8AAAAAAAAE24C4dNQAZoAkdARAAAAAAAAE24C4dNeAVoA0dAgEAAAAAAAE0IB4dNSA1oAkdAJAAAAAAAAE0oCodNeAVoAkdAPAAAAAAAAE24C4dNeAVoA0dAOQAAAAAAAE24C4dLyGgDR0BBAAAAAAAATSADh02QAWgDR0AkAAAAAAAATQgHh0vIaANHQEKAAAAAAABNuAuHTRAOaANHP7mZmZmZmZpNWAKHTUAGaANHQCQAAAAAAABNYAmHTVgCaANHQDwAAAAAAABNkAGHS8hoA0dAMwAAAAAAAE0oCodNkAFoAkdAOQAAAAAAAE2YCIdNgAxoA0dAHAAAAAAAAE2YCIdNWAJoA0c/5mZmZmZmZk24C4dN6ANoAkdAHAAAAAAAAE0sAYdNkAFoAkdAKgAAAAAAAE2YCIdNWAJoA0dAaQAAAAAAAE0IB4dN0AdoA0c/2ZmZmZmZmk2QAYdNgAxoA0dAaQAAAAAAAE3wCodNoA9oAkdAikAAAAAAAE1ABodNYAloAkdAj0AAAAAAAE0oCodNgAxoAkdAQQAAAAAAAE3wCodNkAFoAkdAOQAAAAAAAE24C4dNiBNoAkdAaQAAAAAAAE2wBIdLyGgCR0BCgAAAAAAATZgIh014BWgCR0BpAAAAAAAATbgLh014BWgCR0AqAAAAAAAATbgLh03QB2gCR0AwAAAAAAAATXgFh03oA2gDR0BBAAAAAAAATUAGh03wCmgCR0A/AAAAAAAATQgHh0vIaAJHP/AAAAAAAABNQAaHTegDaAJHQBAAAAAAAABNsASHS8hoA0dAMAAAAAAAAE1YAodLyGgCR0B2gAAAAAAATSgKh00oCmgDR0A2AAAAAAAATSgKh0vIaANHQCQAAAAAAABNWAKHS8hoAkdAPwAAAAAAAE2YCIdLyGgCRz/wAAAAAAAATfAKh024C2gDR0BpAAAAAAAATbAEh03oA2gCR0CAQAAAAAAATSADh00gA2gDR0AQAAAAAAAATZgIh03oA2gCR0BBAAAAAAAATbAEh02QAWgDR0AwAAAAAAAATSADh0vIaAJHQHaAAAAAAABN0AeHTZABaANHQBAAAAAAAABNCAeHTegDaANHQCQAAAAAAABNeAWHTVgCaANHQGkAAAAAAABN6AOHTSADaAJHP+ZmZmZmZmZNCAeHTWAJaANHP9mZmZmZmZpN6AOHTaAPaAJHQIBAAAAAAABN6AOHTVgCaANHQBAAAAAAAABNuAuHTXgFaAJHP9mZmZmZmZpN0AeHS8hoAkdAikAAAAAAAE30AYdNkAFoA0dARAAAAAAAAE24C4dNgAxoAkc/5mZmZmZmZk2YCIdNsARoA0dAKgAAAAAAAE0gA4dNkAFoA0dAPwAAAAAAAE14BYdNWAJoAkdARAAAAAAAAE14BYdNWAJoAkdAdoAAAAAAAE1gCYdN2A5oA0dAKgAAAAAAAE3wCodNeAVoA0dAQQAAAAAAAE3QB4dNQAZoAkdAEAAAAAAAAE3QB4dNSA1oAkdARAAAAAAAAE2YCIdNWAJoA0dAQoAAAAAAAE30AYdLyGgCR0CFQAAAAAAATUAGh03oA2gDR0B2gAAAAAAATfAKh00wEWgCR0BEAAAAAAAATQgHh02QAWgCR0AcAAAAAAAATZABh00gA2gCR0B2gAAAAAAATbAEh02QAWgDR0BBAAAAAAAATXgFh00gA2gDR0AzAAAAAAAATSADh0vIaANHQHaAAAAAAABNYAmHTfAKaANHP/AAAAAAAABNYAmHTSADaANHQCQAAAAAAABN0AeHS8hoAkc/uZmZmZmZmk14BYdLyGgDR0A2AAAAAAAATWAJh03oA2gCR0CFQAAAAAAATWAJh01ABmgDR0A8AAAAAAAATbgLh02wBGgDR0BCgAAAAAAATbAEh014BWgDR0BCgAAAAAAATXgFh03oA2gDRz/ZmZmZmZmaTUAGh00wEWgDR0AcAAAAAAAATdAHh02QAWgDR0AcAAAAAAAATfAKh03oA2gCR0A2AAAAAAAATegDh0vIaAJHQDkAAAAAAABNCAeHTbAEaANHQEKAAAAAAABNYAmHTYAMaAJHQBwAAAAAAABN0AeHTRAOaANHQDMAAAAAAABNYAmHTVgCaANHQGkAAAAAAABNQAaHTdAHaAJHQIBAAAAAAABNKAqHTQgHaAJHQEKAAAAAAABN8AqHTUAGaANHQDYAAAAAAABNIAOHS8hoA0dAHAAAAAAAAE0IB4dLyGgCRz+5mZmZmZmaTfAKh03QB2gCRz/wAAAAAAAATegDh02QAWgCR0AqAAAAAAAATQgHh02wBGgDRz+5mZmZmZmaTSADh01IDWgCR0AwAAAAAAAATWAJh01ABmgCR0CFQAAAAAAATZgIh01ABmgCR0A8AAAAAAAATZABh01YAmgDR0CFQAAAAAAATQgHh024C2gDRz/wAAAAAAAATbgLh00IB2gCR0CPQAAAAAAATSwBh0vIaAJHQIVAAAAAAABNCAeHTegDaANHQDwAAAAAAABNYAmHS8hoA0dAdoAAAAAAAE24C4dNEA5oA0c/uZmZmZmZmk2YCIdNiBNoAkdAhUAAAAAAAE24C4dNYAloA0c/8AAAAAAAAE2YCIdLyGgCR0AkAAAAAAAATfAKh02QAWgDRz+5mZmZmZmaTSwBh02QAWgCR0AkAAAAAAAATWAJh02wBGgDR0A8AAAAAAAATfQBh0vIaAJHP+ZmZmZmZmZNQAaHTegDaAJHP9mZmZmZmZpNKAqHTQgHaAJHQDwAAAAAAABN0AeHS8hoA0dAgEAAAAAAAE0sAYdNIANoA0dARAAAAAAAAE3wCodNaBBoAkdAdoAAAAAAAE0IB4dNsARoA0dAJAAAAAAAAE3oA4dLyGgDR0CAQAAAAAAATVgCh03wCmgCR0CKQAAAAAAATdAHh014BWgDR0AwAAAAAAAATZABh01YAmgCR0CKQAAAAAAATSgKh02YCGgCR0B2gAAAAAAATbgLh00IB2gCR0AQAAAAAAAATSgKh034EWgCR0AwAAAAAAAATZgIh02QAWgDR0AqAAAAAAAATbAEh0vIaAJHQIpAAAAAAABNLAGHTZABaANHQDAAAAAAAABNKAqHTZABaANHQDkAAAAAAABNCAeHS8hoA0dAdoAAAAAAAE30AYdNIANoAkdAdoAAAAAAAE30AYdLyGgDRz/ZmZmZmZmaTbgLh00AGWgDR0A8AAAAAAAATQgHh02QAWgCR0AkAAAAAAAATSADh02QAWgCRz/wAAAAAAAATZgIh01gCWgCR0A8AAAAAAAATSwBh0vIaAJHQDMAAAAAAABNWAKHS8hoA0c/uZmZmZmZmk3wCodNiBNoA0dAQoAAAAAAAE1ABodNQAZoAkdAPAAAAAAAAE1YAodNmAhoA0dARAAAAAAAAE2wBIdN6ANoA0c/8AAAAAAAAE3wCodN6ANoAkdAikAAAAAAAE2QAYdLyGgCR0AzAAAAAAAATSADh0vIaAJHQD8AAAAAAABN0AeHTZABaANHQDkAAAAAAABNeAWHS8hoAkdAikAAAAAAAE1YAodN6ANoA0dARAAAAAAAAE3oA4dNeAVoA0dAQoAAAAAAAE3oA4dNIANoA0dAQQAAAAAAAE3oA4dNkAFoAkc/8AAAAAAAAE0oCodNgAxoAkdAgEAAAAAAAE0IB4dNQAZoA0dAhUAAAAAAAE30AYdNmAhoAkdAhUAAAAAAAE30AYdNkAFoA0dAQQAAAAAAAE0oCodNCAdoAkdAj0AAAAAAAE3QB4dNoA9oA0dAQQAAAAAAAE0IB4dNmAhoAkdAMwAAAAAAAE2YCIdNkAFoAkdAHAAAAAAAAE0gA4dNYAloAkc/uZmZmZmZmk2YCIdNsARoAkdAaQAAAAAAAE2YCIdNIANoAkdAPAAAAAAAAE2YCIdNkAFoAkdAHAAAAAAAAE2YCIdNGBVoA0dAHAAAAAAAAE24C4dN6ANoA0dAHAAAAAAAAE1gCYdNWAJoAkdAHAAAAAAAAE30AYdNkAFoA0dAHAAAAAAAAE30AYdLyGgCRz+5mZmZmZmaTUAGh02wBGgDRz/mZmZmZmZmTUAGh0vIaAJHQEEAAAAAAABNKAqHTVgCaANHQDMAAAAAAABN8AqHTZABaAJHQGkAAAAAAABNCAeHS8hoA0dAhUAAAAAAAE2YCIdNoA9oAkdAgEAAAAAAAE30AYdNkAFoAkdAj0AAAAAAAE2QAYdNIANoA0dAhUAAAAAAAE1ABodNKApoA0c/5mZmZmZmZk2YCIdLyGgCR0AcAAAAAAAATWAJh01IDWgDR0CAQAAAAAAATdAHh02ADGgCR0AkAAAAAAAATfQBh02QAWgDR0A/AAAAAAAATbgLh00oCmgCRz+5mZmZmZmaTSwBh0vIaANHQEKAAAAAAABNmAiHTQgHaANHQIBAAAAAAABNKAqHTTARaANHQD8AAAAAAABNCAeHTZABaAJHP9mZmZmZmZpNmAiHTVgCaANHQCoAAAAAAABNKAqHTQgHaAJHQDkAAAAAAABN6AOHS8hoA0c/uZmZmZmZmk2wBIdNSA1oAkdAEAAAAAAAAE0gA4dNkAFoAkdAPwAAAAAAAE0oCodNIANoA0dAJAAAAAAAAE2wBIdNkAFoA0dARAAAAAAAAE2YCIdNYAloA0dAQoAAAAAAAE0gA4dNeAVoA0dAgEAAAAAAAE2QAYdNWAJoA0dAMAAAAAAAAE0sAYdNWAJoA0dAQoAAAAAAAE1YAodNWAJoAkdAikAAAAAAAE2YCIdN0AdoA0dARAAAAAAAAE0oCodNaBBoAkc/5mZmZmZmZk0oCodNQAZoAkdAj0AAAAAAAE0gA4dNIANoAkdAikAAAAAAAE0IB4dNmAhoA0dAaQAAAAAAAE1gCYdNYAloAkc/8AAAAAAAAE0gA4dLyGgCR0CAQAAAAAAATbgLh00oCmgCR0A2AAAAAAAATSgKh01ABmgCR0AQAAAAAAAATUAGh00oCmgCR0AcAAAAAAAATVgCh03QB2gCR0AzAAAAAAAATWAJh01ABmgDR0CKQAAAAAAATSgKh0vIaANHQD8AAAAAAABN9AGHS8hoA0dAdoAAAAAAAE3QB4dN8ApoAkdAdoAAAAAAAE3oA4dNWAJoAkc/2ZmZmZmZmk1ABodLyGgCR0A2AAAAAAAATZgIh01YAmgCRz/mZmZmZmZmTXgFh03oA2gDR0B2gAAAAAAATZgIh01IDWgCR0CPQAAAAAAATZgIh00wEWgCR0BpAAAAAAAATWAJh02QAWgDR0CAQAAAAAAATSADh03wCmgDR0A/AAAAAAAATSADh0vIaAJHQDMAAAAAAABNKAqHTQgHaANHP+ZmZmZmZmZN8AqHTZABaANHP9mZmZmZmZpNIAOHTaAPaAJHP/AAAAAAAABNeAWHTSADaAJHQI9AAAAAAABNuAuHTdgOaAJHQEEAAAAAAABNYAmHTZABaAJHQGkAAAAAAABNQAaHTZABaANHQIBAAAAAAABNYAmHTRAOaAJHQDkAAAAAAABN8AqHTWAJaANHQD8AAAAAAABNWAKHS8hoA0dAdoAAAAAAAE1YAodNIANoAkdANgAAAAAAAE1YAodLyGgDRz/ZmZmZmZmaTXgFh00QDmgDR0BCgAAAAAAATSgKh01gCWgCR0AqAAAAAAAATfAKh00gA2gDR0CAQAAAAAAATZgIh00QDmgCR0AcAAAAAAAATSgKh00QDmgCR0CPQAAAAAAATVgCh01YAmgCR0CAQAAAAAAATWAJh03wCmgCR0BCgAAAAAAATQgHh02QAWgCR0A2AAAAAAAATWAJh014BWgDR0A2AAAAAAAATZgIh0vIaANHQIBAAAAAAABN9AGHTbAEaAJHQBAAAAAAAABNeAWHTdAHaANHQI9AAAAAAABNCAeHS8hoA0dAEAAAAAAAAE2wBIdNIANoAkdAQQAAAAAAAE2YCIdNCAdoAkdAj0AAAAAAAE14BYdNKApoAkdAQQAAAAAAAE0gA4dNWAJoA0dAhUAAAAAAAE3oA4dNEA5oA0dAhUAAAAAAAE2QAYdNsARoAkdAikAAAAAAAE1gCYdN8ApoAkdAOQAAAAAAAE2wBIdNIANoA0dAEAAAAAAAAE3QB4dNWAJoA0dAKgAAAAAAAE3QB4dNWAJoAkdAKgAAAAAAAE2wBIdLyGgDR0BpAAAAAAAATSADh0vIaAJHQDYAAAAAAABN0AeHS8hoA0c/uZmZmZmZmk14BYdNwBJoAkdAJAAAAAAAAE3QB4dNIANoA0dAOQAAAAAAAE0oCodNIANoA0dAMAAAAAAAAE2YCIdLyGgCR0CAQAAAAAAATVgCh03oA2gCRz/ZmZmZmZmaTXgFh03oA2gCR0B2gAAAAAAATfAKh02gD2gDR0AwAAAAAAAATfQBh03oA2gCR0AwAAAAAAAATfQBh0vIaAJHQBAAAAAAAABNmAiHTdgOaANHQCQAAAAAAABN8AqHTbAEaANHQD8AAAAAAABNYAmHTZABaAJHQDYAAAAAAABNkAGHS8hoAkdAikAAAAAAAE14BYdNeAVoAkdAJAAAAAAAAE2QAYdNWAJoA0dAOQAAAAAAAE3oA4dLyGgDR0AzAAAAAAAATegDh0vIaAJHQCQAAAAAAABNLAGHS8hoA0dANgAAAAAAAE3QB4dNWAJoA0dAPAAAAAAAAE0oCodNkAFoA0dAaQAAAAAAAE0oCodNgAxoA0dARAAAAAAAAE0gA4dNsARoAkc/5mZmZmZmZk0gA4dNkAFoA0c/2ZmZmZmZmk3QB4dNuAtoA0dAPwAAAAAAAE3QB4dNkAFoA0dARAAAAAAAAE1gCYdNmAhoAkdAPwAAAAAAAE1gCYdNWAJoAkc/5mZmZmZmZk2wBIdNkAFoA0dARAAAAAAAAE1YAodLyGgCR0BpAAAAAAAATfAKh00gA2gDR0BCgAAAAAAATQgHh00IB2gCR0AcAAAAAAAATegDh00IB2gCR0A5AAAAAAAATUAGh03oA2gDRz+5mZmZmZmaTUAGh00YFWgDR0CFQAAAAAAATSwBh00gA2gCR0CPQAAAAAAATQgHh00oCmgCR0A8AAAAAAAATSADh00IB2gCR0BCgAAAAAAATbgLh03oA2gCR0A5AAAAAAAATWAJh00QDmgCRz/ZmZmZmZmaTbgLh02YCGgCR0BEAAAAAAAATSADh0vIaAJHQCoAAAAAAABNQAaHS8hoA0dAgEAAAAAAAE2wBIdNKApoA0c/uZmZmZmZmk3oA4dNaBBoA0dAEAAAAAAAAE1YAodLyGgDRz/wAAAAAAAATUAGh00gA2gCR0BCgAAAAAAATWAJh01YAmgDR0AzAAAAAAAATQgHh02QAWgCRz+5mZmZmZmaTWAJh03oA2gCR0AwAAAAAAAATSADh0vIaANHQDwAAAAAAABN0AeHS8hoAkdAJAAAAAAAAE1YAodNCAdoA0c/5mZmZmZmZk0gA4dLyGgCR0A8AAAAAAAATfQBh03oA2gDR0AqAAAAAAAATZgIh03oA2gCR0AqAAAAAAAATWAJh00IB2gDRz+5mZmZmZmaTSgKh02IE2gCR0BpAAAAAAAATegDh0vIaANHQEKAAAAAAABN0AeHTdAHaAJHQDwAAAAAAABNYAmHTSADaANHP/AAAAAAAABNKAqHTVgCaAJHQIBAAAAAAABN0AeHTXgFaAJHQEQAAAAAAABNYAmHTbAEaANHQIBAAAAAAABN8AqHTaAPaAJHQI9AAAAAAABN6AOHTegDaANHQEQAAAAAAABN9AGHTZABaAJHQEQAAAAAAABN9AGHS8hoAkdAikAAAAAAAE24C4dNwBJoA0dAPAAAAAAAAE3wCodNkAFoAkdAdoAAAAAAAE1ABodN6ANoAkdAKgAAAAAAAE0gA4dLyGgDR0B2gAAAAAAATbAEh00IB2gDR0BCgAAAAAAATZABh02QAWgDR0AwAAAAAAAATUAGh0vIaANHQDkAAAAAAABN8AqHTZABaAJHQIVAAAAAAABNsASHS8hoAkdAEAAAAAAAAE3wCodNwBJoA0dAdoAAAAAAAE0gA4dNWAJoA0dAEAAAAAAAAE0oCodNIANoA0dAOQAAAAAAAE1ABodNkAFoAkc/8AAAAAAAAE2wBIdNsARoAkdAhUAAAAAAAE0gA4dNkAFoA0dAPAAAAAAAAE14BYdNkAFoA0dAKgAAAAAAAE0IB4dNIANoA0dAMAAAAAAAAE1gCYdNkAFoAkdAhUAAAAAAAE3QB4dNsARoA0dAdoAAAAAAAE14BYdN2A5oA0dAHAAAAAAAAE2wBIdNWAJoAkc/2ZmZmZmZmk0IB4dN6ANoA0dAgEAAAAAAAE3oA4dNsARoAkdAMwAAAAAAAE3oA4dLyGgDR0A5AAAAAAAATbAEh01YAmgCRz/mZmZmZmZmTVgCh0vIaANHP9mZmZmZmZpNCAeHTcASaAJHQDwAAAAAAABNKAqHTVgCaAJHQHaAAAAAAABNeAWHTVgCaANHQEEAAAAAAABNsASHS8hoAkdAdoAAAAAAAE0gA4dNkAFoAkdAMwAAAAAAAE2wBIdN6ANoA0dAPwAAAAAAAE3wCodN0AdoAkdAHAAAAAAAAE2wBIdN0AdoAkdAhUAAAAAAAE1YAodNsARoAkdAJAAAAAAAAE2YCIdLyGgCR0CFQAAAAAAATfAKh01ABmgCR0CKQAAAAAAATegDh00gA2gDR0BCgAAAAAAATSwBh0vIaANHQEEAAAAAAABN8AqHTWAJaANHQDwAAAAAAABNIAOHS8hoAkdAJAAAAAAAAE0IB4dLyGgDR0BpAAAAAAAATZgIh02gD2gCRz+5mZmZmZmaTQgHh0vIaAJHQEQAAAAAAABNsASHS8hoA0c/uZmZmZmZmk1gCYdNaBBoAkdAhUAAAAAAAE14BYdNQAZoA0dAMwAAAAAAAE24C4dNeAV1Lg=='

class scanpack2(scanpackbase100epj):
    kinds = [set_mfv_neutralino, set_gluino_ddbar]
    taus = [tau/1000. for tau in range(100, 1000, 100) + range(1000, 4000, 1000) + range(40000, 100001, 3000)]
    masses = range(300, 600, 100) + range(600, 2601, 200)

    def events_per_sample(self, kind, tau, mass):
        return 10000

class scanpack2p5(scanpackbase100epj):
    # missing stats from scanpack2 run
    samples_string = 'gAJ9cQEoVRBzZXRfZ2x1aW5vX2RkYmFycQJHQFGAAAAAAABNmAiHTSwBaAJHQFMAAAAAAABNkAGHTbAEVRJzZXRfbWZ2X25ldXRyYWxpbm9xA0dAUYAAAAAAAE0sAYdNEA5oAkdATQAAAAAAAE14BYdLZGgDR0BIgAAAAAAATdAHh03wI2gCR0BLgAAAAAAATZABh0tkaANHQFDAAAAAAABNmAiHTWgQaANHP+zMzMzMzM1N0AeHS2RoA0dAUAAAAAAAAE1ABodLyGgCRz/TMzMzMzMzTZgIh02ADGgCR0BYQAAAAAAATSgKh00EEGgDRz/mZmZmZmZmTdAHh01UJGgDR0BSQAAAAAAATSwBh03QB2gCRz/ZmZmZmZmaTSgKh034EWgCRz/ZmZmZmZmaTVgCh03wCmgDRz/jMzMzMzMzTWAJh020FGgCRz/JmZmZmZmaTdAHh0vIaAJHQEuAAAAAAABNLAGHS2RoAkdAV4AAAAAAAE14BYdLZGgCR0AAAAAAAAAATXgFh0tkaAJHP+MzMzMzMzNNCAeHTbwbaAJHQFGAAAAAAABN9AGHTSwBaANHP+MzMzMzMzNN6AOHTXQOaAJHQFkAAAAAAABNIAOHTUgNaANHP9MzMzMzMzNNsASHTegDaANHQEiAAAAAAABNWAKHTWAiaANHP9mZmZmZmZpNLAGHS8hoA0dAWEAAAAAAAE3QB4dNrA1oA0c/2ZmZmZmZmk2YCIdLyGgCRz/TMzMzMzMzTWAJh020FGgDR0BHAAAAAAAATdAHh02YIWgCRz/ZmZmZmZmaTbAEh01oEGgDR0BQAAAAAAAATegDh0tkaANHP+ZmZmZmZmZNWAKHTRwMaANHQE6AAAAAAABN0AeHS2RoA0dAUAAAAAAAAE14BYdLZGgCR0BZAAAAAAAATZgIh03YDmgDR0BRgAAAAAAATSgKh03gFWgDRz/jMzMzMzMzTVgCh00QDmgCR0BSQAAAAAAATSwBh030AWgDR0BKAAAAAAAATUAGh038IWgDRz/szMzMzMzNTSgKh01sB2gDRz/TMzMzMzMzTVgCh00sAWgCR0BZAAAAAAAATUAGh03QB2gDR0BFgAAAAAAATbAEh0tkaAJHQFkAAAAAAABNLAGHTZABaANHP9MzMzMzMzNNKAqHTTARaANHP/AAAAAAAABN0AeHTZgIaANHQFYAAAAAAABNsASHS8hoA0dAAAAAAAAAAE3oA4dNIANoA0dAWEAAAAAAAE0oCodN8ApoA0dAUwAAAAAAAE2wBIdNrCZoAkdAWQAAAAAAAE2QAYdNkAFoA0c/2ZmZmZmZmk1gCYdNLAFoA0dAUMAAAAAAAE0oCodNiBNoAkc/4zMzMzMzM02QAYdNcBdoA0dARwAAAAAAAE2wBIdNjCNoAkdAUYAAAAAAAE2wBIdNkAFoA0dASIAAAAAAAE1gCYdN8CNoA0dAUwAAAAAAAE3oA4dNcBdoA0dAAAAAAAAAAE0sAYdN6ANoAkc/yZmZmZmZmk0IB4dLyGgCRz/jMzMzMzMzTdAHh00gHGgDRz/wAAAAAAAATQgHh03QB2gCRz/TMzMzMzMzTbAEh0vIaANHP/AAAAAAAABNYAmHTegDaANHP+MzMzMzMzNN9AGHTegDaAJHQFJAAAAAAABNeAWHTfQBaANHQE6AAAAAAABNmAiHS2RoAkdAUYAAAAAAAE1ABodNLAFoAkdAVsAAAAAAAE0oCodLZGgDR0BVQAAAAAAATZgIh0tkaAJHP9MzMzMzMzNNkAGHS8hoA0dAAAAAAAAAAE2QAYdNvAJoA0c/4AAAAAAAAE14BYdLyGgDRz/ZmZmZmZmaTVgCh01YAmgDR0BLgAAAAAAATfQBh01AH2gDRz/mZmZmZmZmTfQBh03wCmgDR0BLgAAAAAAATWAJh0tkaAJHQFGAAAAAAABNeAWHS2RoAkc/2ZmZmZmZmk1gCYdN5AxoAkc/4zMzMzMzM014BYdN+BFoA0dAUYAAAAAAAE0gA4dNCCBoA0dAAAAAAAAAAE1ABodNjApoAkc/2ZmZmZmZmk30AYdNKApoAkdAWEAAAAAAAE14BYdN6ANoAkdAV4AAAAAAAE0oCodNLAFoA0dAUMAAAAAAAE1gCYdNzBBoA0c/8AAAAAAAAE14BYdN3AVoAkc/4AAAAAAAAE14BYdNFB5oA0dASgAAAAAAAE3oA4dNjCNoAkdAUMAAAAAAAE3QB4dNWAJoA0dASIAAAAAAAE0oCodNHCVoA0dARYAAAAAAAE1gCYdLyGgDRz/gAAAAAAAATSgKh01oEGgCR0BWwAAAAAAATVgCh0tkaANHP9mZmZmZmZpN0AeHS2RoA0c/6ZmZmZmZmk2QAYdN9BpoAkc/4zMzMzMzM02YCIdNQB9oA0dAS4AAAAAAAE0gA4dN8CNoAkdAWEAAAAAAAE0IB4dNFAVoAkc/4AAAAAAAAE0IB4dNPA9oA0dAUYAAAAAAAE1gCYdNUBRoAkdAUkAAAAAAAE2QAYdLZGgDR0BIgAAAAAAATUAGh02MI2gDR0BRgAAAAAAATfQBh00MF2gDRz/pmZmZmZmaTQgHh0tkaANHQEcAAAAAAABNYAmHTYwjaANHQFhAAAAAAABNeAWHTSADaANHQFGAAAAAAABNQAaHTUwdaANHQEcAAAAAAABN9AGHTZABaAJHP8mZmZmZmZpNYAmHTSwBaANHQEcAAAAAAABNWAKHTfQBaANHQFAAAAAAAABNYAmHS8hoAkc/0zMzMzMzM014BYdLyGgDR0BYQAAAAAAATZgIh010DmgCR0BQwAAAAAAATSgKh02QAWgCR0BSQAAAAAAATdAHh03cBWgDR0BZAAAAAAAATSwBh00gA2gCR0BUgAAAAAAATZABh0tkaANHQFJAAAAAAABNkAGHTWAJaANHP/AAAAAAAABN9AGHS2RoA0dAVsAAAAAAAE2wBIdLZGgCR0BQAAAAAAAATWAJh0tkaAJHP9MzMzMzMzNNCAeHTfQBaANHP+MzMzMzMzNNLAGHTfQBaANHQFhAAAAAAABNWAKHS8hoA0dAUkAAAAAAAE0gA4dNHAxoA0dARwAAAAAAAE0oCodNVCRoAkdARAAAAAAAAE1ABodLZGgDR0BSQAAAAAAATdAHh01cEmgCR0BZAAAAAAAATegDh03AEmgDRz/TMzMzMzMzTUAGh03cBWgDR0BIgAAAAAAATSADh01gImgDRz/gAAAAAAAATegDh0tkaANHQFGAAAAAAABNsASHTSgjaANHQEiAAAAAAABNeAWHTSgjaANHP9MzMzMzMzNN6AOHTSwBaAJHQFJAAAAAAABNmAiHTWAJaANHQFJAAAAAAABNYAmHTSAcaANHP+MzMzMzMzNNkAGHTUwEaANHQAAAAAAAAABN9AGHTZABaANHP8mZmZmZmZpN9AGHS2RoA0c/2ZmZmZmZmk0gA4dNkAFoA0dAVgAAAAAAAE0oCodLZGgDR0BKAAAAAAAATXgFh00oI2gCR0BYQAAAAAAATZgIh02kBmgDR0BSQAAAAAAATVgCh01IDWgDRz/mZmZmZmZmTXgFh00cJWgDR0BFgAAAAAAATSgKh03oA2gDR0BFgAAAAAAATdAHh0tkaANHP9MzMzMzMzNNYAmHTdgOaANHP+AAAAAAAABNmAiHTSgKaANHQFkAAAAAAABNkAGHTbwCaAJHQFYAAAAAAABN0AeHS2RoA0dARwAAAAAAAE0IB4dNKCNoAkc/4AAAAAAAAE0sAYdN0AdoAkc/2ZmZmZmZmk2QAYdNsARoA0dASIAAAAAAAE2YCIdNgCVoA0c/4AAAAAAAAE1ABodNkAFoAkc/4zMzMzMzM00oCodN5CVoA0c/4zMzMzMzM00gA4dNHAxoA0c/0zMzMzMzM02YCIdN0AdoA0dAS4AAAAAAAE2QAYdNTB1oA0dAUkAAAAAAAE2YCIdNRBZoA0c/8AAAAAAAAE1ABodNjApoA0dAWEAAAAAAAE0IB4dNKApoA0dAVgAAAAAAAE1YAodLZGgCR0BSQAAAAAAATUAGh00gA2gDR0BSQAAAAAAATSgKh00gHGgDR0BHAAAAAAAATegDh03EImgCRz/TMzMzMzMzTUAGh02QAWgDRz/mZmZmZmZmTQgHh03EImgCRz/JmZmZmZmaTegDh0tkaANHP8mZmZmZmZpN0AeHS8hoA0c/5mZmZmZmZk2YCIdNCCBoA0dAU8AAAAAAAE0sAYdLZGgCR0BSQAAAAAAATVgCh0vIaAJHQEWAAAAAAABNsASHTawmaANHQFVAAAAAAABNKAqHS8hoAkdACAAAAAAAAE3QB4dLZGgDR0BLgAAAAAAATVgCh00IIGgCR0BYQAAAAAAATVgCh0tkaAJHP9MzMzMzMzNN6AOHTSwBaANHQFAAAAAAAABNKAqHTbwCaANHQFVAAAAAAABNYAmHS2RoAkc/4zMzMzMzM02wBIdN2A5oA0dAAAAAAAAAAE2wBIdNTARoAkc/4AAAAAAAAE2QAYdNcBdoA0dAUYAAAAAAAE3oA4dNpB9oAkc/8AAAAAAAAE1gCYdLZGgDRz/JmZmZmZmaTSgKh028AmgDRz/ZmZmZmZmaTXgFh00oCmgDRz/mZmZmZmZmTegDh01sIGgCRz/jMzMzMzMzTegDh02ADGgCRz/JmZmZmZmaTUAGh0tkaANHQFMAAAAAAABN9AGHTSQTaANHQFJAAAAAAABN9AGHTVQLaANHQAAAAAAAAABNYAmHS2RoAkdAWEAAAAAAAE3QB4dNsARoAkdAAAAAAAAAAE1gCYdLyGgDR0BKAAAAAAAATQgHh000IWgCRz/gAAAAAAAATdAHh03wI2gCR0BZAAAAAAAATQgHh01kGWgDRz/gAAAAAAAATQgHh01YAmgDRz/wAAAAAAAATegDh00sAWgDR0BLgAAAAAAATSwBh03cHmgDRz/jMzMzMzMzTbAEh03MEGgDRz/szMzMzMzNTWAJh02QAWgCRz/jMzMzMzMzTUAGh03UF2gDR0BXgAAAAAAATSgKh0tkaANHQEWAAAAAAABNWAKHS2RoAkc/2ZmZmZmZmk2YCIdNOBhoA0dAUwAAAAAAAE0gA4dNnBhoA0c/4zMzMzMzM014BYdNDBdoA0dAAAAAAAAAAE0IB4dNPA9oAkc/2ZmZmZmZmk0sAYdN6ANoAkc/5mZmZmZmZk2QAYdNrCZoA0dAUwAAAAAAAE1YAodNqBZoA0dAUMAAAAAAAE0sAYdLyGgDRz/mZmZmZmZmTUAGh02MI2gDRz+5mZmZmZmaTSgKh0tkaANHQFVAAAAAAABNIAOHS2RoAkdAUMAAAAAAAE0IB4dNkAFoAkdAUYAAAAAAAE0IB4dLyGgDR0BKAAAAAAAATVgCh01sIGgCRz/ZmZmZmZmaTegDh01ABmgCR0AIAAAAAAAATSgKh00sAWgCRz/TMzMzMzMzTSgKh02IE2gDR0BQwAAAAAAATdAHh01EFmgDRz/wAAAAAAAATZgIh02kBmgDRz/mZmZmZmZmTSwBh00IB2gDRz/mZmZmZmZmTZABh01IDWgCR0BXgAAAAAAATZgIh0tkaANHP9MzMzMzMzNNeAWHTaQGaANHP9MzMzMzMzNNIAOHS8hoA0c/7MzMzMzMzU2YCIdLyGgCR0BQwAAAAAAATWAJh02QAWgDRz/wAAAAAAAATSgKh010DmgDRz/JmZmZmZmaTegDh0tkaAJHQFhAAAAAAABNIAOHTbAEaANHP9mZmZmZmZpN6AOHTYQDaANHQAgAAAAAAABNKAqHS2RoAkc/4AAAAAAAAE0gA4dNABloA0c/yZmZmZmZmk2YCIdNhANoAkdAWQAAAAAAAE1gCYdNmAhoA0dARAAAAAAAAE0sAYdLZGgCRz/gAAAAAAAATZgIh014HmgDRz/gAAAAAAAATWAJh010DmgCR0BVQAAAAAAATdAHh030AWgCR0BSQAAAAAAATSADh0vIaANHQEoAAAAAAABNLAGHTSgjaAJHP+AAAAAAAABN9AGHTbwbaANHQEiAAAAAAABNLAGHTcQiaANHP9mZmZmZmZpNQAaHTfQBaANHQEoAAAAAAABNmAiHTYwjaANHQEWAAAAAAABNCAeHS8hoAkc/5mZmZmZmZk0sAYdNOBhoA0dAUYAAAAAAAE0IB4dN7BNoA0dAUkAAAAAAAE3oA4dN5AxoA0dAAAAAAAAAAE1YAodNhANoAkdAWEAAAAAAAE1gCYdNFAVoAkc/4AAAAAAAAE1gCYdNnBhoA0dARwAAAAAAAE2QAYdLZGgCR0BYQAAAAAAATfQBh0tkaANHP+mZmZmZmZpNLAGHTYwjaAJHQFJAAAAAAABNYAmHTVQLaAJHQFeAAAAAAABNYAmHTZABaANHP7mZmZmZmZpNmAiHS8hoAkdACAAAAAAAAE0gA4dLZGgDR0BTAAAAAAAATZABh01oEGgDRz/wAAAAAAAATZABh0tkaANHQFPAAAAAAABN0AeHS2RoA0dAWEAAAAAAAE3oA4dNkAFoAkc/4zMzMzMzM01gCYdNKCNoA0c/4zMzMzMzM02YCIdNfBVoA0c/5mZmZmZmZk0oCodNxCJoA0c/4zMzMzMzM00oCodN4BVoA0c/8AAAAAAAAE0gA4dLZGgCR0BZAAAAAAAATbAEh02IE2gCR0BZAAAAAAAATfQBh03ECWgDR0BIgAAAAAAATegDh02MI2gDR0AAAAAAAAAATSADh01YAmgCRz/gAAAAAAAATVgCh01EFmgDRz/ZmZmZmZmaTZABh0vIaAJHQFkAAAAAAABNWAKHTWAJaANHQFAAAAAAAABNmAiHTSwBaAJHP+MzMzMzMzNNLAGHTfQaaAJHQFJAAAAAAABNKAqHTWgQaAJHP+MzMzMzMzNNIAOHTTwPaANHQEoAAAAAAABNkAGHTYwjaAJHQFhAAAAAAABNsASHTVgCaANHQEQAAAAAAABNKAqHS2RoA0dAAAAAAAAAAE3QB4dNWAJoA0dAWEAAAAAAAE1ABodN8ApoA0c/4zMzMzMzM00IB4dNzBBoA0dARwAAAAAAAE2YCIdNVCRoA0dAUwAAAAAAAE0sAYdNuAtoA0dARwAAAAAAAE1ABodNjCNoAkc/2ZmZmZmZmk0gA4dN3AVoAkdAWQAAAAAAAE3QB4dNsB1oAkc/4AAAAAAAAE1ABodNkBpoA0dASIAAAAAAAE0IB4dNjCNoA0c/4AAAAAAAAE3QB4dNsARoA0c/7MzMzMzMzU0IB4dLyGgDR0BRgAAAAAAATZgIh01QFGgCRz/ZmZmZmZmaTUAGh01IDWgDR0BKAAAAAAAATdAHh00cJWgDR0BKAAAAAAAATSgKh03wI2gCRz/ZmZmZmZmaTXgFh00cDGgCRz/gAAAAAAAATSgKh01EFmgCR0BRgAAAAAAATVgCh0vIaANHQFhAAAAAAABNYAmHTcwQaAJHQEWAAAAAAABN6AOHTfQBaANHQAgAAAAAAABNCAeHS2RoA0c/7MzMzMzMzU1ABodLyGgCR0AAAAAAAAAATZgIh0tkaAJHQFAAAAAAAABNQAaHS2RoA0dARwAAAAAAAE14BYdNVCRoA0dAVsAAAAAAAE2YCIdLZGgDR0BHAAAAAAAATSADh02AJWgDRz/pmZmZmZmaTSgKh0tkaANHQAAAAAAAAABNKAqHS2RoA0dAUMAAAAAAAE14BYdN5AxoAkdAUkAAAAAAAE3oA4dNkAFoA0dAUkAAAAAAAE2wBIdNiBNoA0c/yZmZmZmZmk14BYdLZGgDR0BVQAAAAAAATUAGh0tkaAJHQFkAAAAAAABNeAWHTbwbaAJHP9mZmZmZmZpNCAeHTYAMaAJHP9MzMzMzMzNN9AGHS2RoAkdAUYAAAAAAAE0oCodNvAJoA0c/0zMzMzMzM03QB4dNNAhoA0dAUYAAAAAAAE14BYdNCCBoA0dAUkAAAAAAAE1ABodNcBdoA0c/2ZmZmZmZmk2wBIdNFAVoA0c/5mZmZmZmZk0gA4dNlBFoA0dAUYAAAAAAAE1YAodN2A5oAkc/2ZmZmZmZmk3QB4dN7BNoA0dAUYAAAAAAAE2QAYdNLBpoA0c/5mZmZmZmZk2wBIdNCCBoAkdAWEAAAAAAAE3oA4dNFAVoA0c/5mZmZmZmZk1gCYdNbCBoA0dASgAAAAAAAE0gA4dNxCJoAkc/4AAAAAAAAE3oA4dNWBtoA0dAWEAAAAAAAE2wBIdNIANoA0dASIAAAAAAAE2QAYdNYCJoAkdAUMAAAAAAAE1ABodLyGgDR0BWAAAAAAAATWAJh0tkaANHQFDAAAAAAABNsASHTUgNaAJHQFhAAAAAAABNQAaHTUwEaAJHP9MzMzMzMzNNIAOHTSwBaANHQFJAAAAAAABNeAWHTZQRaANHP7mZmZmZmZpNLAGHS2RoA0dAUYAAAAAAAE3QB4dNiBNoA0dASgAAAAAAAE30AYdNYCJoA0dASIAAAAAAAE30AYdN/CFoA0dASgAAAAAAAE1gCYdNxCJoA0c/yZmZmZmZmk1gCYdLZGgDR0BQwAAAAAAATQgHh024C2gCR0BZAAAAAAAATSgKh00cDGgCR0BTAAAAAAAATSwBh02QAWgDRz/ZmZmZmZmaTfQBh00gA2gCRz/jMzMzMzMzTfQBh03YDmgCRz/JmZmZmZmaTSgKh02QAWgDR0BWAAAAAAAATXgFh0vIaANHQFJAAAAAAABNCAeHTcASaANHQAAAAAAAAABNeAWHTbgLaANHQEQAAAAAAABNYAmHS8hoAkdAUMAAAAAAAE2YCIdNLAFoA0c/4zMzMzMzM03QB4dNfBVoAkdAUYAAAAAAAE0gA4dLyGgCR0BRgAAAAAAATdAHh030AWgCR0BSQAAAAAAATfQBh0vIaAJHP7mZmZmZmZpNmAiHS2RoA0dAUMAAAAAAAE3oA4dNvAJoA0c/8AAAAAAAAE2wBIdN3AVoAkdARAAAAAAAAE2YCIdLZGgCR0BRgAAAAAAATWAJh02QAWgCRz/jMzMzMzMzTVgCh02sDWgDRz/gAAAAAAAATbAEh0vIaANHP7mZmZmZmZpNCAeHS2RoAkc/0zMzMzMzM00sAYdLZGgDR0BXgAAAAAAATWAJh0tkaANHQFDAAAAAAABNQAaHTRwMaANHP9MzMzMzMzNNCAeHTWAJaANHP+MzMzMzMzNNQAaHTXwVaANHQEiAAAAAAABNsASHTZghaAJHP7mZmZmZmZpNCAeHS2RoA0dAWQAAAAAAAE30AYdN9AFoA0dAWEAAAAAAAE30AYdLZGgCRz/TMzMzMzMzTdAHh008D2gDRz/pmZmZmZmaTbAEh0vIaAJHP+AAAAAAAABNsASHTYgTaANHQFeAAAAAAABN0AeHS2RoAkdAUAAAAAAAAE0oCodLZGgCR0BSQAAAAAAATQgHh00gA2gDRz/wAAAAAAAATVgCh0vIaANHP+zMzMzMzM1NeAWHS8hoA0dAVIAAAAAAAE3QB4dLZGgCR0BSQAAAAAAATbAEh02QAWgDR0BKAAAAAAAATbAEh00cJWgDRz/JmZmZmZmaTQgHh0vIaANHQFhAAAAAAABNIAOHTfQBaANHQFYAAAAAAABNQAaHTZABaANHQEWAAAAAAABNQAaHS2R1Lg=='

####

def get_scanpack(x):
    return {
        'scanpacktest': scanpacktest,
        'scanpacktest2': scanpacktest2,
        'scanpack1': scanpack1,
        'scanpack1_100epj': scanpack1_100epj,
        'scanpack1p5': scanpack1p5,
        'scanpack2': scanpack2,
        'scanpack2p5': scanpack2p5,
        }[x]()

def do_scanpack(process, x, batch, job):
    sp = get_scanpack(x)
    set_kind, tau, mass = sp.sample(batch, job)
    print 'do_scanpack: %s nbatches %s njobs %s lastjobs %s batch %s job %s kind %s tau %s mass %s' % (x, sp.nbatches, sp.njobs, sp.jobs_in_last_batch, batch, job, set_kind.__name__, tau, mass)
    set_kind(process, tau, mass)

def export_scanpack(crab_dirs):
    from JMTucker.Tools.CRAB3ToolsSh import crab_hadd_files as crab_files

    sample_files = defaultdict(list)

    for wd in crab_dirs:
        bwd = os.path.basename(wd)
        bwd = bwd.replace('crab_', '')
        scanpack, batch = bwd.rsplit('_', 1)
        batch = int(batch)
        scanpack = get_scanpack(scanpack)

        expected, files = crab_files(wd, True)
        assert expected == scanpack.jobs_per_batch or expected == scanpack.jobs_in_last_batch

        for fn in files:
            bn = os.path.basename(fn)
            if not bn.startswith('minitree'):
                continue

            job = int(bn.rsplit('_',1)[-1].replace('.root', '')) - 1
            kind, tau, mass = scanpack.sample(batch, job)
            sample_name = scanpack.sample_name(kind, tau, mass)
            sample_files[sample_name].append(str(fn))

    return dict(sample_files)

def read_scanpack_list(fn):
    if fn.endswith('.gz'):
        f = GzipFile(fn)
    else:
        f = open(fn)
    return eval(f.read())

def hadd_scanpack(lst_fn):
    from JMTucker.Tools import colors, eos
    from JMTucker.Tools.hadd import hadd

    lst = read_scanpack_list(lst_fn)
    new_lst = {}
    hadds = []
    for name, fns in lst.iteritems():
        fns = [str(s) for s in fns]
        out_fn = None
        for fn in fns:
            sfn = fn.split('/')
            assert re.match(r'\d{4}', sfn[-2])
            assert re.match(r'\d{6}_\d{6}', sfn[-3])
            new_out_fn = '/'.join(sfn[:-2]) + '/' + name + '.root'
            if out_fn is None:
                out_fn = new_out_fn
            else:
                assert new_out_fn == out_fn

        new_lst[name] = [out_fn]
        if eos.exists(out_fn):
            print colors.yellow('%s already exists' % out_fn)
        else:
            hadd(out_fn, fns)

    print '\nnew list:'
    pprint(new_lst)

def merge_scanpack_lists(fns):
    lsts = [read_scanpack_list(fn) for fn in fns]
    lst = lsts.pop(0)
    for l in lsts:
        for k in l:
            if lst.has_key(k):
                assert not (set(lst[k]) & set(l[k]))
                lst[k].extend(l[k])
            else:
                lst[k] = l[k]
    return lst

if __name__ == '__main__' and len(sys.argv) > 1:
    cmd = sys.argv[1]

    if cmd == 'export':
        from JMTucker.Tools.CRAB3ToolsSh import crab_dirs_from_argv
        pprint(export_scanpack(crab_dirs_from_argv()))

    elif cmd == 'read':
        x = read_scanpack_list(sys.argv[2])
        for k in sorted(x):
            print k
            for fn in sorted(x[k]):
                print fn

    elif cmd == 'hadd':
        hadd_scanpack(sys.argv[2])

    elif cmd == 'merge':
        x = merge_scanpack_lists(sys.argv[2:])
        pprint(x)

    elif cmd == 'missing':
        fn = sys.argv[2]
        lst = eval(open(fn).read())
        if len(sys.argv) >= 4:
            scanpack = sys.argv[3]
        else:
            scanpack = os.path.basename(fn).replace('.list', '')
        scanpack = get_scanpack(scanpack)
        todo = {}

        for kind, tau, mass in scanpack.samples:
            name = scanpack.sample_name(kind, tau, mass)
            files = lst.get(name, [])
            nevents = scanpack.events_per_job * len(files)
            expected = scanpack.events_per_sample(kind, tau, mass)
            if not files:
                print 'empty', name
            elif expected > nevents:
                missing = todo[(kind.__name__,tau,mass)] = expected - nevents
                print 'incomplete', name, nevents, expected, missing
            elif expected == nevents:
                print 'done', name, expected
            else:
                assert 0

        pprint(todo)
        ps = pickle.dumps(todo, -1)
        print repr(base64.b64encode(ps))

    elif cmd == 'test':
        from gensim import process
        for batch in 0,1: #,2,3: #,4
            for job in xrange(5000):
                print batch, job,
                do_scanpack(process, 'scanpack2p5', batch, job)
