#include "JMTucker/MFVNeutralino/interface/FlatNtuple.h"

// generate with
//   grep 'short\|int\|char\|float\|double\|long\|unsigned\|bool' ../interface/FlatNtuple.h | grep -v \( > editme
//   # edit editme
//   branchcommands.py editme [read]

namespace mfv {
  void write_to_tree(TTree* tree, FlatNtuple& nt) {
    tree->Branch("run", &nt.run, "run/i");
    tree->Branch("lumi", &nt.lumi, "lumi/i");
    tree->Branch("event", &nt.event, "event/i");
    tree->Branch("sample", &nt.sample, "sample/b");
    tree->Branch("gen_valid", &nt.gen_valid, "gen_valid/O");
    tree->Branch("gen_lsp_pt", nt.gen_lsp_pt, "gen_lsp_pt[2]/F");
    tree->Branch("gen_lsp_eta", nt.gen_lsp_eta, "gen_lsp_eta[2]/F");
    tree->Branch("gen_lsp_phi", nt.gen_lsp_phi, "gen_lsp_phi[2]/F");
    tree->Branch("gen_lsp_mass", nt.gen_lsp_mass, "gen_lsp_mass[2]/F");
    tree->Branch("gen_lsp_decay", nt.gen_lsp_decay, "gen_lsp_decay[6]/F");
    tree->Branch("gen_decay_type", nt.gen_decay_type, "gen_decay_type[2]/b");
    tree->Branch("gen_partons_in_acc", &nt.gen_partons_in_acc, "gen_partons_in_acc/b");
    tree->Branch("npu", &nt.npu, "npu/F");
    tree->Branch("bsx", &nt.bsx, "bsx/F");
    tree->Branch("bsy", &nt.bsy, "bsy/F");
    tree->Branch("bsz", &nt.bsz, "bsz/F");
    tree->Branch("npv", &nt.npv, "npv/b");
    tree->Branch("pvx", &nt.pvx, "pvx/F");
    tree->Branch("pvy", &nt.pvy, "pvy/F");
    tree->Branch("pvz", &nt.pvz, "pvz/F");
    tree->Branch("pv_ntracks", &nt.pv_ntracks, "pv_ntracks/b");
    tree->Branch("pv_sumpt2", &nt.pv_sumpt2, "pv_sumpt2/F");
    tree->Branch("jet_id", &nt.jet_id);
    tree->Branch("jet_pt", &nt.jet_pt);
    tree->Branch("jet_eta", &nt.jet_eta);
    tree->Branch("jet_phi", &nt.jet_phi);
    tree->Branch("jet_energy", &nt.jet_energy);
    tree->Branch("metx", &nt.metx, "metx/F");
    tree->Branch("mety", &nt.mety, "mety/F");
    tree->Branch("metsig", &nt.metsig, "metsig/F");
    tree->Branch("metdphimin", &nt.metdphimin, "metdphimin/F");
    tree->Branch("lep_id", &nt.lep_id);
    tree->Branch("lep_pt", &nt.lep_pt);
    tree->Branch("lep_eta", &nt.lep_eta);
    tree->Branch("lep_phi", &nt.lep_phi);
    tree->Branch("lep_dxy", &nt.lep_dxy);
    tree->Branch("lep_dz", &nt.lep_dz);
    tree->Branch("lep_iso", &nt.lep_iso);
    tree->Branch("lep_mva", &nt.lep_mva);
    tree->Branch("nvertices", &nt.nvertices, "nvertices/b");
    tree->Branch("vtx_nmu", &nt.vtx_nmu);
    tree->Branch("vtx_nel", &nt.vtx_nel);
    tree->Branch("vtx_x", &nt.vtx_x);
    tree->Branch("vtx_y", &nt.vtx_y);
    tree->Branch("vtx_z", &nt.vtx_z);
    tree->Branch("vtx_cxx", &nt.vtx_cxx);
    tree->Branch("vtx_cxy", &nt.vtx_cxy);
    tree->Branch("vtx_cxz", &nt.vtx_cxz);
    tree->Branch("vtx_cyy", &nt.vtx_cyy);
    tree->Branch("vtx_cyz", &nt.vtx_cyz);
    tree->Branch("vtx_czz", &nt.vtx_czz);
    tree->Branch("vtx_chi2", &nt.vtx_chi2);
    tree->Branch("vtx_ndof", &nt.vtx_ndof);
    tree->Branch("vtx_njets", &nt.vtx_njets);
    tree->Branch("vtx_tks_pt", &nt.vtx_tks_pt);
    tree->Branch("vtx_tks_eta", &nt.vtx_tks_eta);
    tree->Branch("vtx_tks_phi", &nt.vtx_tks_phi);
    tree->Branch("vtx_tks_mass", &nt.vtx_tks_mass);
    tree->Branch("vtx_jets_pt", &nt.vtx_jets_pt);
    tree->Branch("vtx_jets_eta", &nt.vtx_jets_eta);
    tree->Branch("vtx_jets_phi", &nt.vtx_jets_phi);
    tree->Branch("vtx_jets_mass", &nt.vtx_jets_mass);
    tree->Branch("vtx_tksjets_pt", &nt.vtx_tksjets_pt);
    tree->Branch("vtx_tksjets_eta", &nt.vtx_tksjets_eta);
    tree->Branch("vtx_tksjets_phi", &nt.vtx_tksjets_phi);
    tree->Branch("vtx_tksjets_mass", &nt.vtx_tksjets_mass);
    tree->Branch("vtx_jetpairdetamin", &nt.vtx_jetpairdetamin);
    tree->Branch("vtx_jetpairdetamax", &nt.vtx_jetpairdetamax);
    tree->Branch("vtx_jetpairdetaavg", &nt.vtx_jetpairdetaavg);
    tree->Branch("vtx_jetpairdetarms", &nt.vtx_jetpairdetarms);
    tree->Branch("vtx_jetpairdrmin", &nt.vtx_jetpairdrmin);
    tree->Branch("vtx_jetpairdrmax", &nt.vtx_jetpairdrmax);
    tree->Branch("vtx_jetpairdravg", &nt.vtx_jetpairdravg);
    tree->Branch("vtx_jetpairdrrms", &nt.vtx_jetpairdrrms);
    tree->Branch("vtx_costhtkmomvtxdispmin", &nt.vtx_costhtkmomvtxdispmin);
    tree->Branch("vtx_costhtkmomvtxdispmax", &nt.vtx_costhtkmomvtxdispmax);
    tree->Branch("vtx_costhtkmomvtxdispavg", &nt.vtx_costhtkmomvtxdispavg);
    tree->Branch("vtx_costhtkmomvtxdisprms", &nt.vtx_costhtkmomvtxdisprms);
    tree->Branch("vtx_costhjetmomvtxdispmin", &nt.vtx_costhjetmomvtxdispmin);
    tree->Branch("vtx_costhjetmomvtxdispmax", &nt.vtx_costhjetmomvtxdispmax);
    tree->Branch("vtx_costhjetmomvtxdispavg", &nt.vtx_costhjetmomvtxdispavg);
    tree->Branch("vtx_costhjetmomvtxdisprms", &nt.vtx_costhjetmomvtxdisprms);
    tree->Branch("vtx_gen2ddist", &nt.vtx_gen2ddist);
    tree->Branch("vtx_gen2derr", &nt.vtx_gen2derr);
    tree->Branch("vtx_gen3ddist", &nt.vtx_gen3ddist);
    tree->Branch("vtx_gen3derr", &nt.vtx_gen3derr);
    tree->Branch("vtx_bs2dcompatscss", &nt.vtx_bs2dcompatscss);
    tree->Branch("vtx_bs2dcompat", &nt.vtx_bs2dcompat);
    tree->Branch("vtx_bs2ddist", &nt.vtx_bs2ddist);
    tree->Branch("vtx_bs2derr", &nt.vtx_bs2derr);
    tree->Branch("vtx_pv2dcompatscss", &nt.vtx_pv2dcompatscss);
    tree->Branch("vtx_pv2dcompat", &nt.vtx_pv2dcompat);
    tree->Branch("vtx_pv2ddist", &nt.vtx_pv2ddist);
    tree->Branch("vtx_pv2derr", &nt.vtx_pv2derr);
    tree->Branch("vtx_pv3dcompatscss", &nt.vtx_pv3dcompatscss);
    tree->Branch("vtx_pv3dcompat", &nt.vtx_pv3dcompat);
    tree->Branch("vtx_pv3ddist", &nt.vtx_pv3ddist);
    tree->Branch("vtx_pv3derr", &nt.vtx_pv3derr);
  }

  void read_from_tree(TTree* tree, FlatNtuple& nt) {
    tree->SetBranchAddress("run", &nt.run);
    tree->SetBranchAddress("lumi", &nt.lumi);
    tree->SetBranchAddress("event", &nt.event);
    tree->SetBranchAddress("gen_valid", &nt.gen_valid);
    tree->SetBranchAddress("gen_lsp_pt", nt.gen_lsp_pt);
    tree->SetBranchAddress("gen_lsp_eta", nt.gen_lsp_eta);
    tree->SetBranchAddress("gen_lsp_phi", nt.gen_lsp_phi);
    tree->SetBranchAddress("gen_lsp_mass", nt.gen_lsp_mass);
    tree->SetBranchAddress("gen_lsp_decay", nt.gen_lsp_decay);
    tree->SetBranchAddress("gen_decay_type", nt.gen_decay_type);
    tree->SetBranchAddress("gen_partons_in_acc", &nt.gen_partons_in_acc);
    tree->SetBranchAddress("npu", &nt.npu);
    tree->SetBranchAddress("bsx", &nt.bsx);
    tree->SetBranchAddress("bsy", &nt.bsy);
    tree->SetBranchAddress("bsz", &nt.bsz);
    tree->SetBranchAddress("npv", &nt.npv);
    tree->SetBranchAddress("pvx", &nt.pvx);
    tree->SetBranchAddress("pvy", &nt.pvy);
    tree->SetBranchAddress("pvz", &nt.pvz);
    tree->SetBranchAddress("pv_ntracks", &nt.pv_ntracks);
    tree->SetBranchAddress("pv_sumpt2", &nt.pv_sumpt2);
    tree->SetBranchAddress("jet_id", &nt.jet_id);
    tree->SetBranchAddress("jet_pt", &nt.jet_pt);
    tree->SetBranchAddress("jet_eta", &nt.jet_eta);
    tree->SetBranchAddress("jet_phi", &nt.jet_phi);
    tree->SetBranchAddress("jet_energy", &nt.jet_energy);
    tree->SetBranchAddress("metx", &nt.metx);
    tree->SetBranchAddress("mety", &nt.mety);
    tree->SetBranchAddress("metsig", &nt.metsig);
    tree->SetBranchAddress("metdphimin", &nt.metdphimin);
    tree->SetBranchAddress("lep_id", &nt.lep_id);
    tree->SetBranchAddress("lep_pt", &nt.lep_pt);
    tree->SetBranchAddress("lep_eta", &nt.lep_eta);
    tree->SetBranchAddress("lep_phi", &nt.lep_phi);
    tree->SetBranchAddress("lep_dxy", &nt.lep_dxy);
    tree->SetBranchAddress("lep_dz", &nt.lep_dz);
    tree->SetBranchAddress("lep_iso", &nt.lep_iso);
    tree->SetBranchAddress("lep_mva", &nt.lep_mva);
    tree->SetBranchAddress("nvertices", &nt.nvertices);
    tree->SetBranchAddress("vtx_nmu", &nt.vtx_nmu);
    tree->SetBranchAddress("vtx_nel", &nt.vtx_nel);
    tree->SetBranchAddress("vtx_x", &nt.vtx_x);
    tree->SetBranchAddress("vtx_y", &nt.vtx_y);
    tree->SetBranchAddress("vtx_z", &nt.vtx_z);
    tree->SetBranchAddress("vtx_cxx", &nt.vtx_cxx);
    tree->SetBranchAddress("vtx_cxy", &nt.vtx_cxy);
    tree->SetBranchAddress("vtx_cxz", &nt.vtx_cxz);
    tree->SetBranchAddress("vtx_cyy", &nt.vtx_cyy);
    tree->SetBranchAddress("vtx_cyz", &nt.vtx_cyz);
    tree->SetBranchAddress("vtx_czz", &nt.vtx_czz);
    tree->SetBranchAddress("vtx_chi2", &nt.vtx_chi2);
    tree->SetBranchAddress("vtx_ndof", &nt.vtx_ndof);
    tree->SetBranchAddress("vtx_njets", &nt.vtx_njets);
    tree->SetBranchAddress("vtx_tks_pt", &nt.vtx_tks_pt);
    tree->SetBranchAddress("vtx_tks_eta", &nt.vtx_tks_eta);
    tree->SetBranchAddress("vtx_tks_phi", &nt.vtx_tks_phi);
    tree->SetBranchAddress("vtx_tks_mass", &nt.vtx_tks_mass);
    tree->SetBranchAddress("vtx_jets_pt", &nt.vtx_jets_pt);
    tree->SetBranchAddress("vtx_jets_eta", &nt.vtx_jets_eta);
    tree->SetBranchAddress("vtx_jets_phi", &nt.vtx_jets_phi);
    tree->SetBranchAddress("vtx_jets_mass", &nt.vtx_jets_mass);
    tree->SetBranchAddress("vtx_tksjets_pt", &nt.vtx_tksjets_pt);
    tree->SetBranchAddress("vtx_tksjets_eta", &nt.vtx_tksjets_eta);
    tree->SetBranchAddress("vtx_tksjets_phi", &nt.vtx_tksjets_phi);
    tree->SetBranchAddress("vtx_tksjets_mass", &nt.vtx_tksjets_mass);
    tree->SetBranchAddress("vtx_jetpairdetamin", &nt.vtx_jetpairdetamin);
    tree->SetBranchAddress("vtx_jetpairdetamax", &nt.vtx_jetpairdetamax);
    tree->SetBranchAddress("vtx_jetpairdetaavg", &nt.vtx_jetpairdetaavg);
    tree->SetBranchAddress("vtx_jetpairdetarms", &nt.vtx_jetpairdetarms);
    tree->SetBranchAddress("vtx_jetpairdrmin", &nt.vtx_jetpairdrmin);
    tree->SetBranchAddress("vtx_jetpairdrmax", &nt.vtx_jetpairdrmax);
    tree->SetBranchAddress("vtx_jetpairdravg", &nt.vtx_jetpairdravg);
    tree->SetBranchAddress("vtx_jetpairdrrms", &nt.vtx_jetpairdrrms);
    tree->SetBranchAddress("vtx_costhtkmomvtxdispmin", &nt.vtx_costhtkmomvtxdispmin);
    tree->SetBranchAddress("vtx_costhtkmomvtxdispmax", &nt.vtx_costhtkmomvtxdispmax);
    tree->SetBranchAddress("vtx_costhtkmomvtxdispavg", &nt.vtx_costhtkmomvtxdispavg);
    tree->SetBranchAddress("vtx_costhtkmomvtxdisprms", &nt.vtx_costhtkmomvtxdisprms);
    tree->SetBranchAddress("vtx_costhjetmomvtxdispmin", &nt.vtx_costhjetmomvtxdispmin);
    tree->SetBranchAddress("vtx_costhjetmomvtxdispmax", &nt.vtx_costhjetmomvtxdispmax);
    tree->SetBranchAddress("vtx_costhjetmomvtxdispavg", &nt.vtx_costhjetmomvtxdispavg);
    tree->SetBranchAddress("vtx_costhjetmomvtxdisprms", &nt.vtx_costhjetmomvtxdisprms);
    tree->SetBranchAddress("vtx_gen2ddist", &nt.vtx_gen2ddist);
    tree->SetBranchAddress("vtx_gen2derr", &nt.vtx_gen2derr);
    tree->SetBranchAddress("vtx_gen3ddist", &nt.vtx_gen3ddist);
    tree->SetBranchAddress("vtx_gen3derr", &nt.vtx_gen3derr);
    tree->SetBranchAddress("vtx_bs2dcompatscss", &nt.vtx_bs2dcompatscss);
    tree->SetBranchAddress("vtx_bs2dcompat", &nt.vtx_bs2dcompat);
    tree->SetBranchAddress("vtx_bs2ddist", &nt.vtx_bs2ddist);
    tree->SetBranchAddress("vtx_bs2derr", &nt.vtx_bs2derr);
    tree->SetBranchAddress("vtx_pv2dcompatscss", &nt.vtx_pv2dcompatscss);
    tree->SetBranchAddress("vtx_pv2dcompat", &nt.vtx_pv2dcompat);
    tree->SetBranchAddress("vtx_pv2ddist", &nt.vtx_pv2ddist);
    tree->SetBranchAddress("vtx_pv2derr", &nt.vtx_pv2derr);
    tree->SetBranchAddress("vtx_pv3dcompatscss", &nt.vtx_pv3dcompatscss);
    tree->SetBranchAddress("vtx_pv3dcompat", &nt.vtx_pv3dcompat);
    tree->SetBranchAddress("vtx_pv3ddist", &nt.vtx_pv3ddist);
    tree->SetBranchAddress("vtx_pv3derr", &nt.vtx_pv3derr);
  }
}
