from ROOT import *
TH1.AddDirectory(0)

f = TFile('hogg_default_10.root')
h_dvvc = f.Get('h_c1v_dvv')
h_dphi = f.Get('h_c1v_absdphivv')

f = TFile('hogg_320110_dbv_10.root')
h_diff = f.Get('h_c1v_dvv')
h_uphi = f.Get('h_c1v_absdphivv')

c1 = TCanvas('c1','c1',700,700)
c1.SetTickx()
c1.SetTicky()
h_dvvc.SetStats(0)
h_dvvc.SetLineColor(kBlack)
h_dvvc.SetLineWidth(3)
h_dvvc.Scale(251./h_dvvc.Integral())
h_dvvc.Draw()
h_diff.SetStats(0)
h_diff.SetLineColor(kBlue)
h_diff.SetLineWidth(3)
h_diff.Scale(251./h_diff.Integral())
h_diff.Draw('sames')

l1 = TLegend(0.5,0.8,0.8,0.9)
l1.AddEntry(h_dvvc, 'd_{BV} from actual MC')
l1.AddEntry(h_diff, 'd_{BV} from toy MC')
l1.SetFillColor(0)
l1.Draw()

c2 = TCanvas('c2','c2',700,350)
c2.SetTickx()
c2.SetTicky()
h_difference = TH1F('h_diff', ';d_{VV}^{C} (cm);difference', 6, 0, 0.12)
h_ratio = TH1F('h_ratio', ';d_{VV}^{C} (cm);ratio', 6, 0, 0.12)
for i in range(1,h_ratio.GetNbinsX()+1):
  a = h_diff.GetBinContent(i)
  ea = h_diff.GetBinError(i)
  b = h_dvvc.GetBinContent(i)
  eb = h_dvvc.GetBinError(i)
  h_difference.SetBinContent(i, a-b)
  h_difference.SetBinError(i, sqrt(ea**2 + eb**2))
  h_ratio.SetBinContent(i, a/b)
  h_ratio.SetBinError(i, a/b * sqrt((ea/a)**2 + (eb/b)**2))
  print 'difference in bin %d = %f +/- %f'%(i, h_difference.GetBinContent(i), h_difference.GetBinError(i))
  print 'ratio in bin %d = %f +/- %f'%(i, h_ratio.GetBinContent(i), h_ratio.GetBinError(i))
h_ratio.SetStats(0)
h_ratio.SetLineWidth(3)
h_ratio.Draw('e')

l2 = TLegend(0.2,0.8,0.8,0.9)
l2.AddEntry(h_ratio, 'd_{BV} from toy MC / d_{BV} from actual MC')
l2.SetFillColor(0)
l2.Draw()

line = TLine(0,1,0.12,1)
line.SetLineWidth(2)
line.SetLineStyle(2)
line.Draw()

c4 = TCanvas('c4','c4',700,350)
c4.SetTickx()
c4.SetTicky()
h_difference.SetStats(0)
h_difference.SetLineWidth(3)
h_difference.Draw('e')

l4 = TLegend(0.2,0.8,0.8,0.9)
l4.AddEntry(h_difference, 'd_{BV} from toy MC - d_{BV} from actual MC')
l4.SetFillColor(0)
l4.Draw()

line2 = TLine(0,0,0.12,0)
line2.SetLineWidth(2)
line2.SetLineStyle(2)
line2.Draw()

